### ISSUE TITLE
[1.12.2] IllegalStateException: Keyboard must be created before you can query key state

### ISSUE THREAD

**Issue by LemADEC** [TeamJM/journeymap#152]
#### Describe the problem in repeatable steps:

1. Go in single player
2. Press F11 (full screen) key
=> crash with IllegalStateException

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
```
java.lang.IllegalStateException: Keyboard must be created before you can query key state
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:406)
	at journeymap.client.forge.event.KeyEventHandler.onGuiKeyboardEvent(KeyEventHandler.java:309)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1663_KeyEventHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:513)
```

https://gist.github.com/LemADEC/0437d32815b37b59a90f9ac364aa0efc

Related modpack version: https://www.curseforge.com/minecraft/modpacks/worldwarminecraft/files/2758854

**Comment by mysticdrew** [comment]
This is a known minecraft issue, has nothing to do with journeymap. 
Google "Keyboard must be created before you can query key state" and you will come up with solutions.

**Comment by LemADEC** [comment]
https://www.reddit.com/r/Minecraft/comments/i22w2/rminecraft_please_help_me_whenever_i_press_f11_to/c20cjho/
