### ISSUE TITLE
[1.12.2] Log errors causing game to sporadically freeze for 2-5 seconds.

### ISSUE THREAD

**Issue by bookerthegeek** [TeamJM/journeymap#169]
## Heyo! ##
Seem to be having a bit of an issue, and no idea what is causing it.

#### Versions:
- journeymap-1.12.2-5.5.6
- forge-1.12.2-14.23.5.2847
  
#### Describe the problem in repeatable steps:

1. Install the mods listed [HERE](https://gist.github.com/bookerthegeek/d746987a64e691aed39e290d342a8bf3)
2. Start a new world
3. Look at the log.

#### Relevant errors:
The full log is located [HERE](https://gist.github.com/bookerthegeek/6430b85028ba63aa1c30f6e57d857d39)
This one is repeated about 20 times:
```
[JM-task-4/WARN] [SurfaceRenderer] java.lang.NullPointerException
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getColorMultiplier(VanillaBlockColorProxy.java:126)
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getBlockColor(VanillaBlockColorProxy.java:100)
	at journeymap.client.model.BlockMD.getBlockColor(BlockMD.java:443)
	at journeymap.client.cartography.render.BaseRenderer.setStratumColors(BaseRenderer.java:277)
	at journeymap.client.cartography.Strata.nextUp(Strata.java:209)
	at journeymap.client.cartography.render.SurfaceRenderer.paintStrata(SurfaceRenderer.java:382)
	at journeymap.client.cartography.render.SurfaceRenderer.renderSurface(SurfaceRenderer.java:190)
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:113)
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:86)
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:140)
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:122)
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72)
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:416)
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

And this one hundreds of times:
```[JM-task-4/WARN] [SurfaceRenderer] java.lang.NullPointerException```

After which it then repeats those, continuously in perpetuity.

**Comment by mysticdrew** [comment]
As stated in discord, I need to know which mod is causing this issue and the block or blocks would be nice too, but not fully needed.

**Comment by mysticdrew** [comment]
Any Update to this? I will close in a day or two if there is no update

**Comment by mysticdrew** [comment]
Someone else reported this and they said the blend water option resolved it.

**Comment by mysticdrew** [comment]
Closing because no response.

**Comment by TNTUP** [comment]
Can confirm on 5.7.1 (https://hasteb.in/jayiqaqe.md) Sorry for commenting on a closed issue

Modlist: Minecraft, MCP, FML, MC Forge, JourneyMap, LunatriusCore, ChatLog, Schematica
[screenie](https://i.qcfb.ca/20200515014451.png)

Guessing it doesn't like rendering water surfaces on a 1.15.2 server with a 1.12.2 client (I guess this is maybe caused with ProtocolSupport? so it's not JM's fault)
