### ISSUE TITLE
[1.12.2] Update check timeout causes world to exit

### ISSUE THREAD

**Issue by Monniasza** [TeamJM/journeymap#170]
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.22.1.2838

#### Describe the problem in repeatable steps:

1. Download [this modpack](https://drive.google.com/file/d/1dssY9M2CedtZCTa8_JlSnkIY8Sr0x66V/view?usp=sharing)
2. Unpack the modpack
3. Install the modpack
4. Launch game with modpack from the link
5. Open singleplayer world "Test"
6. Enable auto-updates
7. Relaunch the game and the world
#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

Initial error:

> [18:31:43] [JM-VersionCheck-1/ERROR] [VersionCheck$1] Could not check version URL
java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_202]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_202]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_202]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_202]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_202]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_202]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_202]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_202]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_202]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_202]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_202]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_202]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_202]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_202]
	at java.net.URL.openStream(Unknown Source) ~[?:1.8.0_202]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:128) [VersionCheck$1.class:1.12.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_202]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

[journeymap.log](https://github.com/TeamJM/journeymap/files/4027323/journeymap.log)

### Expected results
World loads completely

### Actual results
World exits with java.nio.ClosedChannelException

**Comment by mysticdrew** [comment]
This is not causing your world to crash... This is just an exception that is logged out when the ssl cannot be retrieved.

**Comment by mysticdrew** [comment]
also.. update to the latest journeymap, you are 4 versions behind.
