### ISSUE TITLE
Creating crash reports but not crashing 1.12.2 mceternal+extra mods 

### ISSUE THREAD

**Issue by FireFrost76** [TeamJM/journeymap#216]
Trying to run McEternal on a server and keep getting a client side issue , no crash reports on server side , game isnt crashing only logging reports . Version: 1.3.5.3
Minecraft Version: 1.12.2
(modded) forge-14.23.5.2847

had a previous issue where had 2 javas 32 bit and 64 bit so java was running multi installed the 32 bit 
 thanks 

<spoiler> 

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: journeymap/client/api/util/PolygonHelper
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: journeymap/client/api/util/PolygonHelper
    at com.feed_the_beast.ftbutilities.integration.JourneyMapIntegration.chunkChanged(JourneyMapIntegration.java:109)
    at com.feed_the_beast.ftbutilities.integration.JourneyMapIntegration.onDataReceived(JourneyMapIntegration.java:172)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4471_JourneyMapIntegration_onDataReceived_UpdateClientDataEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at com.feed_the_beast.ftblib.lib.EventBase.post(EventBase.java:20)
    at com.feed_the_beast.ftbutilities.net.MessageClaimedChunksUpdate.onMessage(MessageClaimedChunksUpdate.java:152)
    at com.feed_the_beast.ftblib.client.FTBLibClient.handleClientMessage(FTBLibClient.java:69)
    at com.feed_the_beast.ftblib.lib.net.MessageToClientHandler.lambda$onMessage$0(MessageToClientHandler.java:19)
    at com.feed_the_beast.ftblib.lib.net.MessageToClientHandler$$Lambda$8212/2070364263.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)</spoiler>

**Comment by FireFrost76** [comment]
added a spoiler but didnt take =(

**Comment by mysticdrew** [comment]
update to journeymap 5.7.1

**Comment by FireFrost76** [comment]
thanks
