### ISSUE TITLE
[1.15.2] Separate Realms Servers Using The Same Maps

### ISSUE THREAD

**Issue by RoverMaelstrom** [TeamJM/journeymap#221]
#### Describe the problem in repeatable steps:

1. Be a member of two realms servers owned by different people, with different names.
2. Log into one, explore a bit, set some waypoints.
3. Log into the other - it'll show the waypoints and map from the first server and then start overwriting that data with the data from the new server.
4. Log into the first server - the overwritten data will show on the first server then start re-writing itself as you explore the area again.

#### Folder Structure (since this was asked by the discord mod - I only included the stuff that looked relevant, didn't think it was necessary to type out all the default config files and stuff but I can if it proves relevant)

C:\Users\russe\AppData\Roaming\.minecraft\journeymap ->
config
data
icon
server
journeymap.txt

data ->
mp
sp

data -> mp -> offline ->
DIM0
waypoints

DIM0 ->
0 -> 
0,0.png

2 -> 
0,0.png

3 -> 
0,0.png
1,-1.png

4 ->
0,0.png
-1,0.png

day ->
0,0.png
0,-1.png
0,-2.png
1,0.png
-1,0.png
1,-1.png
1,-2.png

night ->
0,0.png
0,-1.png
0,-2.png
1,0.png
-1,0.png
1,-1.png
1,-2.png

topo ->
0,0.png
0,-1.png
0,-2.png
1,0.png
-1,0.png
1,-1.png
1,-2.png

waypoints ->
ALL THE SHEEP_597,83,-85.json
Pirate Ship_572,64,-405.json

#### Relevant error messages from .minecraft\journeymap\journeymap:

[13:41:11] [Render thread/INFO] [JourneymapClient] Mapping halted in C:\Users\russe\AppData\Roaming\.minecraft\journeymap\data\mp\offline\DIM0
[13:41:11] [Render thread/ERROR] [WorldData] Unable to get Realms server name: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: selectedServerId
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:242)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:87)
	at journeymap.client.data.WorldData.getServerName(WorldData.java:165)
	at journeymap.client.data.WorldData.getWorldName(WorldData.java:270)
	at journeymap.client.io.FileHandler.getJMWorldDirForWorldId(FileHandler.java:244)
	at journeymap.client.io.FileHandler.getJMWorldDir(FileHandler.java:212)
	at journeymap.client.io.FileHandler.getJMWorldDir(FileHandler.java:195)
	at journeymap.client.cartography.color.ColorPalette.getWorldPaletteFile(ColorPalette.java:289)
	at journeymap.client.cartography.color.ColorPalette.getActiveColorPalette(ColorPalette.java:190)
	at journeymap.client.JourneymapClient.stopMapping(JourneymapClient.java:566)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:36)
	at net.minecraftforge.eventbus.ASMEventHandler_18_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.Minecraft.func_213231_b(Minecraft.java:1678)
	at net.minecraft.client.Minecraft.func_213254_o(Minecraft.java:1660)
	at net.minecraft.client.gui.screen.IngameMenuScreen.func_213067_a(SourceFile:77)
	at net.minecraft.client.gui.screen.IngameMenuScreen$$Lambda$3695/1778251368.onPress(Unknown Source)
	at net.minecraft.client.gui.widget.button.Button.onPress(SourceFile:18)
	at net.minecraft.client.gui.widget.button.AbstractButton.onClick(SourceFile:15)
	at net.minecraft.client.gui.widget.Widget.mouseClicked(Widget.java:136)
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(SourceFile:27)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)
	at net.minecraft.client.MouseHelper$$Lambda$3060/834072264.run(Unknown Source)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$3059/1924009991.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$2642/1645577752.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105)
	at net.minecraft.client.MainWindow.func_227802_e_(SourceFile:301)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$401/248487859.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
Caused by: java.lang.NoSuchFieldException: selectedServerId
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:236)
	... 49 more

**Comment by mysticdrew** [comment]
Update to beta 3 and see if this issue is resolved, i thought I fixed this in beta 2. Closing, will reopen if it is still an issue.
