### ISSUE TITLE
Dragging on  "dimension" button causes CTD

### ISSUE THREAD

**Issue by schradieck** [TeamJM/journeymap#222]
fairly simple and highly repeatable, click and drag on the "dimesnion" button in the waypoint manager and get an instant crash to desktop
  
#### JourneyMap Version:
journeymap-1.15.2-5.7.0b2

#### Forge Version:
31.1.46

#### Describe the problem in repeatable steps:

open a world.
open journeymap waypoint manager
click and drag on the "Dimensions" button

<details> 
---- Minecraft Crash Report ----
// My bad.

Time: 5/4/20 7:23 PM
Description: mouseDragged event handler

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51] {}
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51] {}
	at journeymap.client.ui.component.ScrollListPane.getSlot(ScrollListPane.java:197) ~[?:1.15.2-5.7.0b2] {re:classloading}
	at journeymap.client.ui.component.ScrollListPane.mouseDragged(ScrollListPane.java:184) ~[?:1.15.2-5.7.0b2] {re:classloading}
	at journeymap.client.ui.waypoint.WaypointManager.mouseDragged(WaypointManager.java:334) ~[?:1.15.2-5.7.0b2] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$cursorPosCallback$9(MouseHelper.java:192) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$11064/1819600801.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198022_b(MouseHelper.java:190) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$2(MouseHelper.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$8079/1124830490.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$3(MouseHelper.java:158) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$7941/101946866.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(SourceFile:301) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.46.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1216139639.call(Unknown Source) [forge-1.15.2-31.1.46.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at journeymap.client.ui.component.ScrollListPane.getSlot(ScrollListPane.java:197)
	at journeymap.client.ui.component.ScrollListPane.mouseDragged(ScrollListPane.java:184)
	at journeymap.client.ui.waypoint.WaypointManager.mouseDragged(WaypointManager.java:334)
	at net.minecraft.client.MouseHelper.lambda$cursorPosCallback$9(MouseHelper.java:192)
	at net.minecraft.client.MouseHelper$$Lambda$11064/1819600801.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: journeymap.client.ui.waypoint.WaypointManager
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198022_b(MouseHelper.java:190)
	at net.minecraft.client.MouseHelper.lambda$null$2(MouseHelper.java:159)
	at net.minecraft.client.MouseHelper$$Lambda$8079/1124830490.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$3(MouseHelper.java:158)
	at net.minecraft.client.MouseHelper$$Lambda$7941/101946866.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['OmniDwarf'/375, l='MpServer', x=4.50, y=70.00, z=-254.50]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 8392813916890165904
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,70,-256), Chunk: (at 0,4,0 in 0,-16; contains blocks 0,0,-256 to 15,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2275 game time, 2275 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1216139639.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1450958920 bytes (1383 MB) / 6020923392 bytes (5742 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.46.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.46.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.46.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.46.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.46.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.46
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.1
	Mod List: 
		CyclopsCore-1.15.2-1.6.2.jar Cyclops Core {cyclopscore@1.6.2 DONE}
		glasscutter-1.0.1-1.15.2.jar Glasscutter {glasscutter@1.0.1 DONE}
		UnionLib-1.15.2-1.2.0.jar UnionLib {unionlib@1.2.0 DONE}
		dotHack-Weapons-1.15.2-1.3.2.jar dotHack Weapons {dothack@1.0.0 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
		CasinoCraft_1.15.2_v08.jar CasinoCraft {casinocraft@v08 DONE}
		ForgeEndertech-1.15.2-6.0.2.2-build.0030.jar Forge Endertech {forgeendertech@6.0.2.2 DONE}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 DONE}
		Controlling-6.1.4.jar Controlling {controlling@6.1.4 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		potionofbees-1.15.2-1.0.0.jar Potion of Bees {potionofbees@1.15.2-1.0.0 DONE}
		NomadicTents-1.15.2-11.0.0-beta.jar Nomadic Tents {nomadictents@11.0.0-beta DONE}
		Bookshelf-1.15.2-5.5.33.jar Bookshelf {bookshelf@5.5.33 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		DarkUtilities-1.15.2-3.0.5.jar Dark Utilities {darkutils@3.0.5 DONE}
		Apotheosis-1.15.2-3.0.7.jar Apotheosis {apotheosis@3.0.7 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		PickUpNotifier-v1.1.2-1.15.2.jar Pick Up Notifier {pickupnotifier@1.1.2 DONE}
		MekanismGenerators-1.15.2-9.10.1.414.jar Mekanism: Generators {mekanismgenerators@9.10.1 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		refinedstorage-1.8.3.jar Refined Storage {refinedstorage@1.8.3 DONE}
		PrettyPipes-1.3.0.jar Pretty Pipes {prettypipes@1.3.0 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.15.2-2.3.0-6f57752.jar Industrial Foregoing {industrialforegoing@2.3.0 DONE}
		TipTheScales-1.15.2-2.0.1.jar TipTheScales {tipthescales@1.15.2-2.0.1 DONE}
		improved-stations-1.1.jar Improved Stations {improved-stations@1.1 DONE}
		CommonCapabilities-1.15.2-2.4.4.jar CommonCapabilities {commoncapabilities@2.4.4 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		GymCraft 1.15.2 (31.1.43).jar GymCraft {gymcraft@1.15.5 DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 DONE}
		Botania-r1.15-383.jar Botania {botania@r1.15-383 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		flying_things-1.8.7-1.15.2.jar The Flying Things {flying_things@1.8.7 DONE}
		roadstuff-1.15.2-3.1.0.jar Road Stuff {roadstuff@1.15.2-3.1.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 DONE}
		MekanismTools-1.15.2-9.10.1.414.jar Mekanism: Tools {mekanismtools@9.10.1 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		ChunkNoGoByeBye-1.15.2-1.2.0.jar ChunkNoGoByeBye {chunknogobyebye@1.15.2-1.2.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		AdChimneys-1.15.2-5.0.4.0-build.0032.jar Advanced Chimneys {adchimneys@5.0.4.0 DONE}
		tramplestopper-1.15.2-2.0.0.1-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		getinthebucketmod-1.15.2-2.2.0.jar Get In The Bucket Mod {getinthebucketmod@2.2.0 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		Cyclic-1.15.2-0.4.1.jar Cyclic {cyclic@1.15.2-0.4.1 DONE}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 DONE}
		CraftPresence-1.15.2-1.6.1.jar CraftPresence {craftpresence@property(class java.lang.String, provider(?)) DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		compact-3.0.jar Compact {compact@3.0 DONE}
		Cucumber-1.15.2-3.0.5.jar Cucumber Library {cucumber@3.0.5 DONE}
		pamhc2trees-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		Overloaded-1.15.2-0.0.86.jar Overloaded {overloaded@1.15.2-0.0.84 DONE}
		Mine and Slash-1.15.2-3.6.14.jar Mine and Slash {mmorpg@3.6.14 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Mekanism-1.15.2-9.10.1.414.jar Mekanism {mekanism@9.10.1 DONE}
		WAWLA-1.15.2-3.0.2.jar WAWLA {wawla@3.0.2 DONE}
		fablibrary-1.15.2-1.1.jar FAB Library {fablibrary@1.1 DONE}
		extraboats-1.3.4-1.15.2.jar Extra Boats {extraboats@1.3.4 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		DimStorage-1.15.2-3.1.2.jar DimStorage {dimstorage@3.1.2 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		FarmingForBlockheads_1.15.2-6.1.2.jar Farming for Blockheads {farmingforblockheads@6.1.2 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		alib-1.15.2-1.jar A Lib {alib@1.15.2-1 DONE}
		nhacampfire_1.15-2.1.jar No Hostiles Around Campfire {nhacampfire@2.1 DONE}
		mcjtylib-1.15-4.0.3-alpha.jar McJtyLib {mcjtylib@1.15-4.0.3-alpha DONE}
		rftoolsbase-1.15-1.0.1-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.1-alpha DONE}
		rftoolsstorage-1.15-1.0.3-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.3-alpha DONE}
		mapperbase-1.15.2-1.1.0.0.jar Mapper Base {mapperbase@1.15.2-1.1.0.0 DONE}
		bedspreads-FORGE-1.15.2-3.0.0.1.jar Bedspreads {bedspreads@FORGE-1.15.2-3.0.0.1 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		mininggadgets-1.3.5.jar Mining Gadgets {mininggadgets@1.3.5 DONE}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha DONE}
		forge-1.15.2-31.1.46-universal.jar Forge {forge@31.1.46 DONE}
		Bountiful-1.15.2-3.1.0.jar Bountiful {bountiful@1.15.2-3.1.0 DONE}
		MysticalAgriculture-1.15.2-3.0.3.jar Mystical Agriculture {mysticalagriculture@3.0.3 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		alchemistry-1.15.2-5.jar Alchemistry {alchemistry@1.15.2-5 DONE}
		forge-1.15.2-31.1.46-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		logprot-1.15.1-1.2.jar Logprot {logprot@1.2 DONE}
		rftoolsutility-1.15-2.0.1-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.1-alpha DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.4.0.jar Titanium {titanium@2.4.0 DONE}
		mcpaint-1.5.0.jar Mc Paint {mcpaint@1.5.0 DONE}
		instahouses-1.15.2-1.1.1.jar Slashkings InstaHouses {instahouses@1.1 DONE}
		compactores-1.15.2-2.1.1.jar Compact Ores {compactores@2.1.1 DONE}
		pamhc2crops-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		AdLods-1.15.2-3.0.3.0-build.0035.jar Large Ore Deposits {adlods@3.0.3.0 DONE}
		Ding-1.15.2-1.1.0.jar Ding {ding@1.1.0 DONE}
		rftoolsbuilder-1.15-2.0.1-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.1-alpha DONE}
		extragolems-10.1.1.jar Extra Golems {golems@10.1.1 DONE}
		pamhc2foodcore-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		chemlib-1.15.2-3.jar Chem Lib {chemlib@1.15.2-3 DONE}
		corail_recycler-4.0.4-1.15.2.jar Corail Recycler {corail_recycler@4.0.4 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-235.jar Quark {quark@r2.1-235 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		DoubleSlabs-1.15-2.2.6.jar Double Slabs {doubleslabs@2.2.6 DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		Harvest-forge-1.15.1-1.2.11-24.jar Harvest {harvest@version DONE}
		PickleTweaks-1.15.2-4.0.2.jar Pickle Tweaks {pickletweaks@4.0.2 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		solcarrot-1.15.2-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.15.2-1.9.4 DONE}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		EnderMail-1.15.2-1.1.0.jar Ender Mail {endermail@1.15.2-1.1.0 DONE}
	Launched Version: forge-31.1.46
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz

</details>

**Comment by mysticdrew** [comment]
Duplicate #207
