### ISSUE TITLE
journeymap encountered an error processing deferred work

### ISSUE THREAD

**Issue by syi666** [TeamJM/journeymap#233]
MC 1.15.2

#### JourneyMap Version:

1.14.4-5.7.0b2

#### Forge Version:

31.2.0

#### Describe the problem in repeatable steps:

1.journeymap encountered an error processing deferred work
2.journeymap encountered an error processing deferred work
3.journeymap encountered an error processing deferred work

```
[17May2020 17:42:10.622] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Syi666, --version, MultiMC5, --gameDir, C:/Users/Syi/Downloads/mmc-stable-win32/MultiMC/instances/1.15.2/.minecraft, --assetsDir, C:/Users/Syi/Downloads/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.15, --uuid, b8c72937426f42d9bd0e41d966835af7, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601, --width, 854, --height, 480]
[17May2020 17:42:10.624] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_231 by Oracle Corporation
[17May2020 17:42:10.802] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[17May2020 17:42:11.713] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, C:\Users\Syi\Downloads\mmc-stable-win32\MultiMC\instances\1.15.2\.minecraft, --assetsDir, C:\Users\Syi\Downloads\mmc-stable-win32\MultiMC\assets, --uuid, b8c72937426f42d9bd0e41d966835af7, --username, Syi666, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[17May2020 17:42:12.792] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Syi666
[17May2020 17:42:17.006] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[17May2020 17:42:17.660] [modloading-worker-9/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 31.2.0, for MC 1.15.2 with MCP 20200515.085601
[17May2020 17:42:17.660] [modloading-worker-9/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.2.0 Initialized
[17May2020 17:42:18.917] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[17May2020 17:42:18.953] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[17May2020 17:42:18.977] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Syi\Downloads\mmc-stable-win32\MultiMC\instances\1.15.2\.minecraft\config\forge-client.toml is not correct. Correcting
[17May2020 17:42:18.978] [Server-Worker-7/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.experimentalForgeLightPipelineEnabled was corrected from null to false
[17May2020 17:42:18.983] [Server-Worker-7/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[17May2020 17:42:18.984] [Thread-2/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[17May2020 17:42:18.987] [Thread-2/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[17May2020 17:42:19.012] [modloading-worker-2/ERROR] [journeymap/]: Found @journeymap.client.api.ClientPlugin: journeymap.client.api.ClientPlugin, but it doesn't implement IClientPlugin
[17May2020 17:42:19.012] [modloading-worker-2/INFO] [journeymap/]: No plugins for JourneyMap API discovered.
[17May2020 17:42:19.102] [Server-Worker-7/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Dispatching synchronous work after COMMON_SETUP: 1 jobs
[17May2020 17:42:19.102] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[17May2020 17:42:19.150] [Render thread/INFO] [journeymap/]: Initializing Packet Registry
[17May2020 17:42:19.158] [Server-Worker-7/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.051
[17May2020 17:42:19.732] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 31.2.0 Target: null
[17May2020 17:42:21.161] [Server-Worker-4/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Dispatching synchronous work after COMPLETE: 1 jobs
[17May2020 17:42:21.170] [Render thread/INFO] [journeymap/]: PostInit
[17May2020 17:42:21.292] [Render thread/INFO] [journeymap/]: JourneyMap log initialized.
[17May2020 17:42:21.293] [Render thread/INFO] [journeymap/]: initialize ENTER
[17May2020 17:42:21.346] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
[17May2020 17:42:21.346] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at journeymap.client.model.GridSpec$Style.<clinit>(GridSpec.java:122)
[17May2020 17:42:21.346] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at journeymap.client.model.GridSpecs.<clinit>(GridSpecs.java:13)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at journeymap.client.properties.CoreProperties.<init>(CoreProperties.java:229)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at journeymap.client.JourneymapClient.loadConfigProperties(JourneymapClient.java:709)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at journeymap.client.JourneymapClient.init(JourneymapClient.java:176)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at journeymap.client.JourneymapClient.lambda$loadCompleteEvent$0(JourneymapClient.java:148)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$6(DeferredWorkQueue.java:210)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[17May2020 17:42:21.347] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
[17May2020 17:42:21.348] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[17May2020 17:42:21.348] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[17May2020 17:42:21.348] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[17May2020 17:42:21.348] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[17May2020 17:42:21.348] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:897)
[17May2020 17:42:21.348] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraft.client.main.Main.main(SourceFile:204)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[17May2020 17:42:21.349] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[17May2020 17:42:21.350] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17May2020 17:42:21.350] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[17May2020 17:42:21.350] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[17May2020 17:42:21.350] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39)
[17May2020 17:42:21.350] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17May2020 17:42:21.350] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17May2020 17:42:21.350] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:toString:25]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:checkErrors:55]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.ITextureObject
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:checkErrors:55]: 	at java.lang.ClassLoader.findClass(Unknown Source)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:checkErrors:55]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17May2020 17:42:21.351] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:checkErrors:55]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[17May2020 17:42:21.352] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:checkErrors:55]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17May2020 17:42:21.352] [Render thread/INFO] [STDERR/]: [journeymap.common.log.LogFormatter:checkErrors:55]: 	... 36 more
[17May2020 17:42:21.352] [Render thread/ERROR] [journeymap/]: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
	at journeymap.client.model.GridSpec$Style.<clinit>(GridSpec.java:122)
	at journeymap.client.model.GridSpecs.<clinit>(GridSpecs.java:13)
	at journeymap.client.properties.CoreProperties.<init>(CoreProperties.java:229)
	at journeymap.client.JourneymapClient.loadConfigProperties(JourneymapClient.java:709)
	at journeymap.client.JourneymapClient.init(JourneymapClient.java:176)
	at journeymap.client.JourneymapClient.lambda$loadCompleteEvent$0(JourneymapClient.java:148)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$6(DeferredWorkQueue.java:210)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:897)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.ITextureObject
	at java.lang.ClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more

[17May2020 17:42:21.353] [Render thread/ERROR] [net.minecraftforge.fml.DeferredWorkQueue/]: Encountered exception executing deferred work
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$6(DeferredWorkQueue.java:210) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:897) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.2.0-launcher.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39) [ForgeWrapper-1.4.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/ITextureObject
	at journeymap.client.model.GridSpec$Style.<clinit>(GridSpec.java:122) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.model.GridSpecs.<clinit>(GridSpecs.java:13) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.properties.CoreProperties.<init>(CoreProperties.java:229) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.JourneymapClient.loadConfigProperties(JourneymapClient.java:709) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.JourneymapClient.init(JourneymapClient.java:176) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.JourneymapClient.lambda$loadCompleteEvent$0(JourneymapClient.java:148) ~[?:1.14.4-5.7.0b2]
	... 30 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.ITextureObject
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at journeymap.client.model.GridSpec$Style.<clinit>(GridSpec.java:122) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.model.GridSpecs.<clinit>(GridSpecs.java:13) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.properties.CoreProperties.<init>(CoreProperties.java:229) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.JourneymapClient.loadConfigProperties(JourneymapClient.java:709) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.JourneymapClient.init(JourneymapClient.java:176) ~[?:1.14.4-5.7.0b2]
	at journeymap.client.JourneymapClient.lambda$loadCompleteEvent$0(JourneymapClient.java:148) ~[?:1.14.4-5.7.0b2]
	... 30 more
[17May2020 17:42:21.355] [Server-Worker-4/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.193
[17May2020 17:42:21.355] [Server-Worker-4/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event COMPLETE, 1 errors found
[17May2020 17:42:21.355] [Server-Worker-4/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_231]
[17May2020 17:42:21.451] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[17May2020 17:42:21.452] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[17May2020 17:42:21.559] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[17May2020 17:42:21.654] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[17May2020 17:42:21.655] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17May2020 17:42:21.658] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17May2020 17:42:21.662] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17May2020 17:42:21.663] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17May2020 17:42:21.664] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17May2020 17:42:21.951] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17May2020 17:42:21.955] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17May2020 17:42:21.956] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas


```

**Comment by gdude2002** [comment]
You're using a 1.14.4 JourneyMap on Forge for 1.15.2. Install a version of JourneyMap intended for Minecraft 1.15.2 instead.
