### ISSUE TITLE
[1.12.2] Sevtech Skyblock cause JM to CTD

### ISSUE THREAD

**Issue by Pultex** [TeamJM/journeymap#306]
#### JourneyMap Version:
journeymap-1.12.2-5.5.4
and
journeymap-1.12.2-5.7.1

#### Forge Version:

forge-14.23.5.2854

#### Describe the problem in repeatable steps:
Using the Fullscreen/window of the map then moving the mouse to the top of the map will cause a CTD

seems world gen made some thing JM does not understand

1.have Journey Map open to fullscreen
2.move mouse over several areas of the map
3.server halts and crashes to desktop

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
`[08:06:36] [Client thread/ERROR] [LayerDelegate] java.lang.NullPointerException
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.generateIslandPositions(SkyIslandGeneratorV2.java:732)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.getIslandPositions(SkyIslandGeneratorV2.java:768)
	at com.bloodnbonesgaming.topography.world.layer.GenLayerBiomeSkyIslands.func_75904_a(GenLayerBiomeSkyIslands.java:36)
	at net.minecraft.world.biome.BiomeProvider.func_76931_a(BiomeProvider.java:128)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at net.minecraft.world.biome.BiomeProvider.func_180300_a(BiomeProvider.java:65)
	at net.minecraft.world.biome.BiomeProvider.func_180631_a(BiomeProvider.java:60)
	at journeymap.client.world.JmBlockAccess.getBiome(JmBlockAccess.java:95)
	at journeymap.client.ui.fullscreen.layer.BlockInfoLayer.onMouseMove(BlockInfoLayer.java:138)
	at journeymap.client.ui.fullscreen.layer.LayerDelegate.onMouseMove(LayerDelegate.java:71)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146286_b(Fullscreen.java:1123)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146274_d(Fullscreen.java:1043)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[08:06:42] [Client thread/ERROR] [LayerDelegate] java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.islandPostionAcceptable(SkyIslandGeneratorV2.java:750)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.generateIslandPositions(SkyIslandGeneratorV2.java:718)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.getIslandPositions(SkyIslandGeneratorV2.java:768)
	at com.bloodnbonesgaming.topography.world.layer.GenLayerBiomeSkyIslands.func_75904_a(GenLayerBiomeSkyIslands.java:36)
	at net.minecraft.world.biome.BiomeProvider.func_76931_a(BiomeProvider.java:128)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at net.minecraft.world.biome.BiomeProvider.func_180300_a(BiomeProvider.java:65)
	at net.minecraft.world.biome.BiomeProvider.func_180631_a(BiomeProvider.java:60)
	at journeymap.client.world.JmBlockAccess.getBiome(JmBlockAccess.java:95)
	at journeymap.client.ui.fullscreen.layer.BlockInfoLayer.onMouseMove(BlockInfoLayer.java:138)
	at journeymap.client.ui.fullscreen.layer.LayerDelegate.onMouseMove(LayerDelegate.java:71)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146286_b(Fullscreen.java:1123)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146274_d(Fullscreen.java:1043)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[08:06:42] [Client thread/ERROR] [LayerDelegate] java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.islandPostionAcceptable(SkyIslandGeneratorV2.java:745)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.generateIslandPositions(SkyIslandGeneratorV2.java:718)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.getIslandPositions(SkyIslandGeneratorV2.java:768)
	at com.bloodnbonesgaming.topography.world.layer.GenLayerBiomeSkyIslands.func_75904_a(GenLayerBiomeSkyIslands.java:36)
	at net.minecraft.world.biome.BiomeProvider.func_76931_a(BiomeProvider.java:128)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at net.minecraft.world.biome.BiomeProvider.func_180300_a(BiomeProvider.java:65)
	at net.minecraft.world.biome.BiomeProvider.func_180631_a(BiomeProvider.java:60)
	at journeymap.client.world.JmBlockAccess.getBiome(JmBlockAccess.java:95)
	at journeymap.client.ui.fullscreen.layer.BlockInfoLayer.onMouseMove(BlockInfoLayer.java:138)
	at journeymap.client.ui.fullscreen.layer.LayerDelegate.onMouseMove(LayerDelegate.java:71)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146286_b(Fullscreen.java:1123)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146274_d(Fullscreen.java:1043)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[08:06:42] [Client thread/ERROR] [LayerDelegate] java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.islandPostionAcceptable(SkyIslandGeneratorV2.java:750)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.generateIslandPositions(SkyIslandGeneratorV2.java:718)
	at com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.getIslandPositions(SkyIslandGeneratorV2.java:768)
	at com.bloodnbonesgaming.topography.world.layer.GenLayerBiomeSkyIslands.func_75904_a(GenLayerBiomeSkyIslands.java:36)
	at net.minecraft.world.biome.BiomeProvider.func_76931_a(BiomeProvider.java:128)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at net.minecraft.world.biome.BiomeProvider.func_180300_a(BiomeProvider.java:65)
	at net.minecraft.world.biome.BiomeProvider.func_180631_a(BiomeProvider.java:60)
	at journeymap.client.world.JmBlockAccess.getBiome(JmBlockAccess.java:95)
	at journeymap.client.ui.fullscreen.layer.BlockInfoLayer.onMouseMove(BlockInfoLayer.java:138)
	at journeymap.client.ui.fullscreen.layer.LayerDelegate.onMouseMove(LayerDelegate.java:71)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146286_b(Fullscreen.java:1123)
	at journeymap.client.ui.fullscreen.Fullscreen.func_146274_d(Fullscreen.java:1043)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

note:
I removed the map data to see if rebuilding would fix it, that did not work
newer version than the one provided in the pack did not fix it either

**Comment by mysticdrew** [comment]
First off, use pastebin, do not paste the log in the issue, it is a pain to read... 
Secondly, it looks like an interaction with
The below mod
com.bloodnbonesgaming.topography.world.generator.SkyIslandGeneratorV2.generateIslandPositions(SkyIslandGeneratorV2.java:732)

Finally, this is for 1.12.2, it will not be receiving any more update, Journeymap has moved on and only developing for 1.16.5 currently. 
Report it to the SkyIslandGen mod if they are still updating their mod for 1.12.2

**Comment by mysticdrew** [comment]
That other mod seems to be causing an issue with biomes. All we are doing is requesting biome data from MC, if they are modifying it, it is on them to resolve it so other mods can get biome data.
