### ISSUE TITLE
[1.12.2] Cilent crash and throw strange message

### ISSUE THREAD

**Issue by Ex-Infinityy** [TeamJM/journeymap#31]
#### JourneyMap Version:

`1.12.2-5.5.2`

#### Forge Version:

`1.12.2-14.23.2.2611`

#### Describe the problem in repeatable steps:

1. [17:31:06] [JM-VersionCheck-1/ERROR] [VersionCheck$1] Could not check version URL
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:134) [VersionCheck$1.class:1.12.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
	... 7 more

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[17:30:12] [main/INFO] [JMLogger] JourneyMap log initialized.
[17:30:12] [main/INFO] [JourneymapClient] initialize ENTER
[17:30:12] [main/WARN] [PropertiesBase] core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[17:30:12] [main/WARN] [PropertiesBase] core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[17:30:12] [Client thread/INFO] [?] Version: JourneyMap 1.12.2-5.5.2, built with Forge 14.23.0.2491
Forge: 14.23.2.2611
Environment: os.name, os.arch, java.version, user.country, user.language=null, game language=en_us, locale=en_us
Features: 
	RadarPlayers : singleplayer = true , multiplayer = true
	RadarAnimals : singleplayer = true , multiplayer = true
	RadarMobs : singleplayer = true , multiplayer = true
	RadarVillagers : singleplayer = true , multiplayer = true
	MapTopo : singleplayer = true , multiplayer = true
	MapSurface : singleplayer = true , multiplayer = true
	MapCaves : singleplayer = true , multiplayer = true
MiniMapProperties{state=Valid, file=journeymap.minimap.config, configVersion=5.5.2, zoomLevel=0, showPlayers=true, frameAlpha=100, compassFontScale=1, terrainAlpha=100, showEntityNames=true, enabled=true, showPlayerHeading=true, showVillagers=true, info2Label=Game Time, sizePercent=30, showDayNight=true, info3Label=Location, showMobs=true, showPets=true, preferredMapType=day, showCompass=true, mobDisplay=Small Dots, showReticle=true, orientation=North, shape=Circle, showSelf=true, info4Label=Biome, locationFormat=xzyv, playerDisplay=Small Dots, showGrid=true, reticleOrientation=Compass, showWaypoints=true, showCaves=true, showAnimals=true, showMobHeading=true, showWaypointLabels=true, locationFormatVerbose=true, position=Top Right, info1Label=Blank, fontScale=1}
MiniMapProperties{state=Valid, file=journeymap.minimap2.config, configVersion=5.5.2, zoomLevel=0, showPlayers=true, frameAlpha=100, compassFontScale=1, terrainAlpha=100, showEntityNames=true, enabled=true, showPlayerHeading=true, showVillagers=true, info2Label=Game Time, sizePercent=30, showDayNight=true, info3Label=Location, showMobs=true, showPets=true, preferredMapType=day, showCompass=true, mobDisplay=Small Dots, showReticle=true, orientation=North, shape=Rectangle, showSelf=true, info4Label=Biome, locationFormat=xzyv, playerDisplay=Small Dots, showGrid=true, reticleOrientation=Compass, showWaypoints=true, showCaves=true, showAnimals=true, showMobHeading=true, showWaypointLabels=true, locationFormatVerbose=true, position=Top Right, info1Label=Blank, fontScale=1}
FullMapProperties{state=Valid, file=journeymap.fullmap.config, configVersion=5.5.2, mobDisplay=Small Dots, zoomLevel=0, showPlayers=true, showSelf=true, locationFormat=xzyv, playerDisplay=Small Dots, showGrid=true, showEntityNames=true, showPlayerHeading=true, showVillagers=true, showWaypoints=true, showCaves=true, showAnimals=true, showMobHeading=true, showKeys=true, showWaypointLabels=true, locationFormatVerbose=true, showMobs=true, showPets=true, fontScale=1, preferredMapType=day}
WaypointProperties{state=Valid, file=journeymap.waypoint.config, configVersion=5.5.2, createDeathpoints=true, showName=true, maxDistance=0, autoHideLabel=true, showStaticBeam=true, minDistance=4, boldLabel=false, textureSmall=true, showDistance=true, showRotatingBeam=true, fontScale=2, showTexture=true, managerEnabled=true, beaconEnabled=true}
WebMapProperties{state=Valid, file=journeymap.webmap.config, configVersion=5.5.2, zoomLevel=0, showWaypoints=true, showCaves=true, showSelf=true, port=8080, showGrid=true, showEntityNames=true, enabled=false, googleMapApiDomain=.com, preferredMapType=day}
CoreProperties{state=Valid, file=journeymap.core.config, configVersion=5.5.2, verboseColorPalette=false, maxPlayersData=32, mapSurfaceAboveCaves=true, optionsManagerViewed=null, announceMod=true, colorPassive=#bbbbbb, renderOverlayEventTypeName=ALL, mapBlendWater=false, renderDistanceSurfaceMax=7, radarVerticalDistance=16, mapBlendGrass=true, recordCacheStats=false, hideSneakingEntities=true, revealShape=Circle, alwaysMapSurface=false, colorVillager=#88e188, mapPlants=false, colorPet=#0077ff, radarLateralDistance=64, mapBathymetry=false, mapCrops=true, maxMobsData=32, mapPlantShadows=false, alwaysMapCaves=false, checkUpdates=true, browserPoll=2000, mapBlendFoliage=true, mappingEnabled=true, colorPlayer=#ffffff, tileHighDisplayQuality=true, cacheVillagersData=2200, logLevel=INFO, maxVillagersData=32, maxAnimalsData=32, mapTransparency=true, tileRenderType=1, caveIgnoreGlass=true, mapTopography=true, renderDistanceCaveMax=3, mapAntialiasing=true, colorSelf=#0000ff, cachePlayersData=2000, cacheMobsData=3000, cachePlayerData=1000, splashViewed=null, colorHostile=#ff0000, cacheAnimalsData=3100, themeName=OceanMonument, mapCaveLighting=true, renderDelay=2, renderOverlayPreEvent=true, autoMapPoll=2000}
[17:30:12] [main/INFO] [ClientAPI] [ClientAPI] built with JourneyMap API 1.4
[17:30:12] [main/INFO] [PluginHelper] Initializing plugins with Client API: journeymap.client.api.impl.ClientAPI
[17:30:12] [main/INFO] [JourneymapClient] initialize EXIT, elapsed count 0 avg ?ms
[17:30:12] [main/TRACE] [LoadController] Sent event FMLInitializationEvent to mod journeymap
[17:30:13] [main/TRACE] [LoadController] Sending event IMCEvent to mod journeymap
[17:30:13] [main/TRACE] [LoadController] Sent event IMCEvent to mod journeymap
[17:31:03] [main/TRACE] [LoadController] Sending event FMLPostInitializationEvent to mod journeymap
[17:31:03] [main/DEBUG] [JourneymapClient] postInitialize ENTER
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.forge.event.KeyEventHandler
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.forge.event.ChatEventHandler
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.forge.event.StateTickHandler
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.forge.event.WorldEventHandler
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.forge.event.WaypointBeaconHandler
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.forge.event.TextureAtlasHandler
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.forge.event.MiniMapOverlayHandler
[17:31:03] [main/DEBUG] [EventHandlerManager] Handler registered: journeymap.client.world.ChunkMonitor
[17:31:04] [main/INFO] [IconSetFileHandler] Added entity icons from journeymap:icon/entity. Success: false
[17:31:04] [main/TRACE] [ThemeLoader] Initializing themes ...
[17:31:04] [main/INFO] [ThemeLoader] Preloaded theme textures: 71
[17:31:05] [main/DEBUG] [StatTimer] elapsed was slow: 2064.778462
[17:31:05] [main/DEBUG] [JourneymapClient] postInitialize EXIT, elapsed§8 count §r1§8 avg §r§r2064.78§8ms§r
[17:31:06] [JM-VersionCheck-1/ERROR] [VersionCheck$1] Could not check version URL
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:134) [VersionCheck$1.class:1.12.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
	... 7 more

**Comment by mysticdrew** [comment]
That's not a crash. It's just an error in the logs.

**Comment by Ex-Infinityy** [comment]
not a crash???
[17:31:05] [main/DEBUG] [JourneymapClient] postInitialize **EXIT**, elapsed§8 count §r1§8 avg §r§r2064.78§8ms§r
[17:31:06] [JM-VersionCheck-1/**ERROR**] [VersionCheck$1] Could not check version URL
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:134) [VersionCheck$1.class:1.12.2-5.5.2]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
... 7 more

**Comment by mysticdrew** [comment]
That error does not cause a crash, it's a common exception.
If you're crashing something else is causing it. 

Maybe give us the full log.
