### ISSUE TITLE
[1.10.2] teleported me to loading screen then Decocraft canopy bed instead of waypoint, camera displaced from server player, unable to rejoin server after death

### ISSUE THREAD

**Issue by SmileyTrek** [TeamJM/journeymap#327]
#### JourneyMap Version:

`1.10.2-5.5.2`

#### Forge Version:

`1.10.2-12.18.3.2511`

#### Describe the problem in repeatable steps:
Maybe have SkyFactory 3 installed? This was played on an automatically created SkyFactory 3 v3.0.21 server.

1. Have a canopy bed from Decocraft placed (I have no idea what happens if you don't have a canopy bed from Decocraft placed, I tried reproducing this without a canopy bed on singleplayer and it worked fine though)
2. Make a waypoint anywhere and teleport to it

After this a loading screen will open for roughly 10-20 seconds, and then you'll spawn at the canopy bed. At this point the two other players in the server were called over by me to the canopy bed. I had moved off the canopy bed and was apparently invisible to them, though I could interact with stuff so I didn't realize it until they said they didn't see me. To them I was still on the canopy bed, but I was wearing no armor (they should've seen me with armor), I wasn't moving, and the gamertag wasn't above my head. They could however, hit the player instance or whatever that was on the canopy bed and I took damage. I couldn't see what they saw though.

3. Kill yourself (specifically in my case I was killed by another person)
4. Go back to the menu while on the death screen as it will not allow you to respawn.
5. try to rejoin the server and it won't let you. it'll give you a Connection Lost error (or at least me):

```Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(35) + length(8) exceeds writerIndex(36): UnpooledHeapByteBuf(ridx: 35, widx: 36, cap: 36))```

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

I don't know how to tell which lines are relevant so here's the entire file. I tried restarting my launcher after the error before I pulled this file so because the timestamps are different between the relevant server.log excerpt and this journeymap log file maybe that means the file got overwritten and nothing useful is left? sorry:
```
[21:03:35] [Client thread/INFO] [JMLogger] JourneyMap log initialized.
[21:03:35] [Client thread/INFO] [JourneymapClient] initialize ENTER
[21:03:35] [Client thread/INFO] [?] Version: JourneyMap 1.10.2-5.5.2, built with Forge 12.18.3.2316
Forge: 12.18.3.2511
Environment: os.name, os.arch, java.version, user.country, user.language=null, game language=en_US, locale=en_us
Features: 
	RadarPlayers : singleplayer = true , multiplayer = true
	RadarAnimals : singleplayer = true , multiplayer = true
	RadarMobs : singleplayer = true , multiplayer = true
	RadarVillagers : singleplayer = true , multiplayer = true
	MapTopo : singleplayer = true , multiplayer = true
	MapSurface : singleplayer = true , multiplayer = true
	MapCaves : singleplayer = true , multiplayer = true
MiniMapProperties{state=Valid, file=journeymap.minimap.config, configVersion=5.5.2, zoomLevel=0, showPlayers=true, frameAlpha=100, compassFontScale=1, terrainAlpha=100, showEntityNames=true, enabled=true, showPlayerHeading=true, showVillagers=true, info2Label=Game Time, sizePercent=30, showDayNight=true, info3Label=Location, showMobs=true, showPets=true, preferredMapType=day, showCompass=true, mobDisplay=Small Dots, showReticle=true, orientation=North, shape=Square, showSelf=true, info4Label=Biome, locationFormat=xzyv, playerDisplay=Small Dots, showGrid=false, reticleOrientation=Compass, showWaypoints=true, showCaves=true, showAnimals=true, showMobHeading=true, showWaypointLabels=true, locationFormatVerbose=true, position=Top Right, info1Label=Blank, fontScale=1}
MiniMapProperties{state=Valid, file=journeymap.minimap2.config, configVersion=5.5.2, zoomLevel=0, showPlayers=true, frameAlpha=100, compassFontScale=1, terrainAlpha=100, showEntityNames=true, enabled=true, showPlayerHeading=true, showVillagers=true, info2Label=Game Time, sizePercent=30, showDayNight=true, info3Label=Location, showMobs=true, showPets=true, preferredMapType=day, showCompass=true, mobDisplay=Small Dots, showReticle=true, orientation=North, shape=Rectangle, showSelf=true, info4Label=Biome, locationFormat=xzyv, playerDisplay=Small Dots, showGrid=true, reticleOrientation=Compass, showWaypoints=true, showCaves=true, showAnimals=true, showMobHeading=true, showWaypointLabels=true, locationFormatVerbose=true, position=Top Right, info1Label=Blank, fontScale=1}
FullMapProperties{state=Valid, file=journeymap.fullmap.config, configVersion=5.5.2, mobDisplay=Small Dots, zoomLevel=3, showPlayers=true, showSelf=true, locationFormat=xzyv, playerDisplay=Small Dots, showGrid=true, showEntityNames=true, showPlayerHeading=true, showVillagers=true, showWaypoints=true, showCaves=true, showAnimals=true, showMobHeading=true, showKeys=true, showWaypointLabels=true, locationFormatVerbose=true, showMobs=true, showPets=true, fontScale=1, preferredMapType=day}
WaypointProperties{state=Valid, file=journeymap.waypoint.config, configVersion=5.5.2, createDeathpoints=true, showName=true, maxDistance=0, autoHideLabel=true, showStaticBeam=true, minDistance=4, boldLabel=false, textureSmall=true, showDistance=true, showRotatingBeam=true, fontScale=2, showTexture=true, managerEnabled=true, beaconEnabled=true}
WebMapProperties{state=Valid, file=journeymap.webmap.config, configVersion=5.5.2, zoomLevel=0, showWaypoints=true, showCaves=true, showSelf=true, port=8080, showGrid=true, showEntityNames=true, enabled=false, googleMapApiDomain=.com, preferredMapType=day}
CoreProperties{state=Valid, file=journeymap.core.config, configVersion=5.5.2, verboseColorPalette=false, maxPlayersData=32, mapSurfaceAboveCaves=true, optionsManagerViewed=5.5.2, announceMod=true, colorPassive=#bbbbbb, renderOverlayEventTypeName=ALL, mapBlendWater=false, renderDistanceSurfaceMax=7, radarVerticalDistance=16, mapBlendGrass=true, recordCacheStats=false, hideSneakingEntities=true, revealShape=Circle, alwaysMapSurface=false, colorVillager=#88e188, mapPlants=false, colorPet=#0077ff, radarLateralDistance=64, mapBathymetry=false, mapCrops=true, maxMobsData=32, mapPlantShadows=false, alwaysMapCaves=false, checkUpdates=true, browserPoll=2000, mapBlendFoliage=true, mappingEnabled=true, colorPlayer=#ffffff, tileHighDisplayQuality=true, cacheVillagersData=2200, logLevel=INFO, maxVillagersData=32, maxAnimalsData=32, mapTransparency=true, tileRenderType=1, caveIgnoreGlass=true, mapTopography=true, renderDistanceCaveMax=3, mapAntialiasing=true, colorSelf=#0000ff, cachePlayersData=2000, cacheMobsData=3000, cachePlayerData=1000, splashViewed=5.5.2, colorHostile=#ff0000, cacheAnimalsData=3100, themeName=EndCity, mapCaveLighting=true, renderDelay=2, renderOverlayPreEvent=true, autoMapPoll=2000}
[21:03:36] [Client thread/INFO] [ClientAPI] [ClientAPI] built with JourneyMap API 1.4
[21:03:36] [Client thread/INFO] [PluginHelper] Initializing plugins with Client API: journeymap.client.api.impl.ClientAPI
[21:03:36] [Client thread/INFO] [PluginHelper] Initialized IClientPlugin: com.feed_the_beast.ftbu.integration.JourneyMapIntegration
[21:03:36] [Client thread/INFO] [JourneymapClient] initialize EXIT, elapsed count 0 avg �ms
[21:03:48] [Client thread/ERROR] [FileHandler] Couldn't locate icons for Default: /Users/milesregal/Documents/curseforge/minecraft/Instances/FTB%20Presents%20SkyFactory%203/mods/journeymap-1.10.2-5.5.2.jar/assets/journeymap/icon/entity
[21:03:48] [Client thread/INFO] [IconSetFileHandler] Added entity icons from journeymap:icon/entity. Success: false
[21:03:48] [Client thread/ERROR] [FileHandler] Couldn't locate icons for flat: /Users/milesregal/Documents/curseforge/minecraft/Instances/FTB%20Presents%20SkyFactory%203/mods/journeymap-1.10.2-5.5.2.jar/assets/journeymap/theme/flat
[21:03:48] [Client thread/INFO] [ThemeLoader] Preloaded theme textures: 0
[21:03:48] [JM-VersionCheck-1/ERROR] [VersionCheck$1] Could not check version URL
java.io.IOException: Server returned HTTP response code: 403 for URL: http://widget.mcf.li/mc-mods/minecraft/journeymap.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840) ~[?:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433) ~[?:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431) ~[?:1.8.0_74]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_74]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782) ~[?:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430) ~[?:1.8.0_74]
	at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_74]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:125) [VersionCheck$1.class:1.10.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[21:04:52] [Client thread/INFO] [ColorManager] Loaded color palette for 1382 blockstates in 282ms
[21:10:38] [Client thread/INFO] [TopoRenderer] Loading journeymap.topo.config
[21:10:38] [Client thread/INFO] [WaypointStore] Loaded 1 waypoints from /Users/milesregal/Documents/curseforge/minecraft/Instances/FTB Presents SkyFactory 3/journeymap/data/sp/Mod Testing/waypoints
[21:10:38] [Client thread/INFO] [JourneymapClient] Mapping started in /Users/milesregal/Documents/curseforge/minecraft/Instances/FTB Presents SkyFactory 3/journeymap/data/sp/Mod Testing/DIM0. Memory: 3460MB total, 1647MB free 
[21:10:38] [Client thread/INFO] [ChatLog] JourneyMap: Press [J]
[21:10:57] [Client thread/INFO] [StateTickHandler] BeastBoyMiles died at BlockPos{x=206, y=-278, z=264}. Deathpoints enabled: true. Deathpoint created: true
[21:11:09] [Client thread/INFO] [JourneymapClient] Mapping halted in /Users/milesregal/Documents/curseforge/minecraft/Instances/FTB Presents SkyFactory 3/journeymap/data/sp/Mod Testing/DIM0
```
---------------------------------------
Also my friend who was on the server with me took a look at the server log and pulled out an excerpt for me. His username and mine have been replaced with placeholders.
```
 [journeymap]: Player1 (Me) joining dimension -343800852
[20:56:26] [Server thread/INFO] [journeymap]: Player1 (Me) joining dimension 0
[20:56:26] [Server thread/INFO] [BloodMagic|API]: Creating demon will cache for world -343800852
[20:57:46] [Server thread/INFO]: Player1 (Me) was slain by Player2
[20:57:56] [Netty Server IO #8/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_201]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[minecraft_server.1.10.2.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [minecraft_server.1.10.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [minecraft_server.1.10.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [minecraft_server.1.10.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [minecraft_server.1.10.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [minecraft_server.1.10.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.1.10.2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[20:57:56] [Server thread/INFO]: Player1 (Me) lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[20:57:56] [Server thread/INFO]: Player1 (Me) left the game
[20:58:10] [User Authenticator #5/INFO]: UUID of player Player1 (Me) is 1a5e4eb8-a13c-44b0-a61e-cc243cdadb67
[20:58:10] [Server thread/WARN]: handleDisconnection() called twice
[20:58:35] [Server thread/INFO]: com.mojang.authlib.GameProfile@32a84d95[id=1a5e4eb8-a13c-44b0-a61e-cc243cdadb67,name=Player1 (Me),properties={textures=[com.mojang.authlib.properties.Property@79e14315]},legacy=false] (/69.5.123.35:57904) lost connection: Disconnected
[20:58:40] [User Authenticator #6/INFO]: UUID of player Player1 (Me) is 1a5e4eb8-a13c-44b0-a61e-cc243cdadb67
[20:58:40] [Server thread/WARN]: handleDisconnection() called twice
[20:58:59] [Server thread/INFO]: com.mojang.authlib.GameProfile@6d7fef47[id=1a5e4eb8-a13c-44b0-a61e-cc243cdadb67,name=Player1 (Me),properties={textures=[com.mojang.authlib.properties.Property@6c31124f]},legacy=false] (/69.5.123.35:57908) lost connection: Disconnected
[21:05:02] [User Authenticator #7/INFO]: UUID of player Player1 (Me) is 1a5e4eb8-a13c-44b0-a61e-cc243cdadb67
[21:05:02] [Server thread/WARN]: handleDisconnection() called twice
[21:05:31] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@7e559aaf[id=1a5e4eb8-a13c-44b0-a61e-cc243cdadb67,name=Player1 (Me),properties={textures=[com.mojang.authlib.properties.Property@1bcea5c6]},legacy=false] (/69.5.123.35:58019): Took too long to log in
[21:05:31] [Server thread/INFO]: com.mojang.authlib.GameProfile@7e559aaf[id=1a5e4eb8-a13c-44b0-a61e-cc243cdadb67,name=Player1 (Me),properties={textures=[com.mojang.authlib.properties.Property@1bcea5c6]},legacy=false] (/69.5.123.35:58019) lost connection: Took too long to log in
```

**Comment by mysticdrew** [comment]
Attach your debug.log and latest.log from both the client and server to this issue. 

Keep in mind, 1.10.2 is no longer supported, it's quite old. But, with that I'm not entirely convinced this issue is with journeymap. I'll take a look at the log files just in case.

**Comment by SmileyTrek** [comment]
My Client latest.log:
[latest.log](https://github.com/TeamJM/journeymap/files/7182124/latest.log)

Neither me nor my friend could find a debug.log file in our computer's files.
I'm not very knowledgeable in these things, but my friend says you don't need the latest.log file because he gave you the server log file excerpt.

**Comment by SmileyTrek** [comment]
Also me and my friend found out that the canopy bed maybe probably has nothing to do with the bug because we found out restarting the server fixes it. He had already removed the bed but I was able to recreate the bug. He could move me using a saddle thing from another mod and it moved my camera and the player instance but once I got off the player instance was just floating. every thing else was the same.

**Comment by mysticdrew** [comment]
Looking through the logs, without having access to the server's log I can only conclude that this is not related to journeymap. 
It looks like maybe another mod is interfering with the spawn packet as per the error. Journeymap does not do anything with the spawn packet. You may need to contact the pack maker and see if this issue has been reported, they may have a solution. 
`at net.minecraft.network.play.server.SPacketSpawnObject.func_148837_a(SourceFile:93) ~[fn.class:?]\`

**Comment by SmileyTrek** [comment]
Thank you
