### ISSUE TITLE
[1.16.5] Freeze (without recovery) when drawing some entities

### ISSUE THREAD

**Issue by GAsplund** [TeamJM/journeymap#364]
#### JourneyMap Version:

`1.16.5-5.8.0beta3`

#### Forge Version:

`1.16.5-36.2.20`

#### Describe the problem in repeatable steps:

1. Fly around in the world
2. Render new chunks
3. The game will freeze

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

The log seemingly does not display any relevant errors. For the sake of it, I have uploaded the full (but rather short) log below:
https://gist.github.com/GAsplund/e5a9437805862f269819f0148cf84b12

The game freezes with the following call stack captured in VisualVM:
![image](https://user-images.githubusercontent.com/7264745/146013869-cb3d19d3-5ae3-4963-a13d-1a85696ed042.png)

**Comment by mysticdrew** [comment]
Can you replicate this with only journeymap and no other mods installed?

**Comment by mysticdrew** [comment]
It's likely not journeymap causing the issue especially getting cached data. If you add all your mods back and remove journeymap, does it still happen?

**Comment by GAsplund** [comment]
I did this, and I was unable to reproduce the issue. I flew around for far longer than I managed to do previously, even trying to deliberately break it. Would there be any other way of tracing where this would come from, or does it seem like a dead end? Other than manually finding the exact combination by enabling and disabling mods, of course.

**Comment by mysticdrew** [comment]
Yea the best way to narrow it down would be to disable half your mods a time to narrow it down. 
It seems really strange that it would lock up when reading from cache. Unless another mod is deliberately interacting with journeymap's cache for some reason and causing a lock up. 

Could you get you debug log next time it locks up. ./minecraft/logs/debug.log

**Comment by GAsplund** [comment]
I got some more development on the situation, and I've come to the conclusion that it's got something to do with some mod after updating Forge. I've been using my current collection of mods since August, and this issue started only happening recently when I updated both Forge and JM. I decided to revert (Back to 5.7.1) with nothing else changed and it seems that Forge changed some behavior in another mod that has lead to this issue. 

Now I suspect that this is going to take a while until the offending mod is found (the pack has just above 200 mods), so is there any possible workaround for now?

Also: [latest.log](https://github.com/TeamJM/journeymap/files/7714726/latest.log)

**Comment by mysticdrew** [comment]
I cannot even comment on a workaround as I have no idea what the actual issue is related to. 
I would start by removing Optifine as there are a ton of optifine errors in your log. There is no release for optifine for forge past 36.1.0. Optifine can be pretty particular about forge versions.

**Comment by GAsplund** [comment]
I have done some extensive testing, and I think that I have narrowed it down properly. It seems that the Smooth Boot mod is causing the freeze, even though it should only affect the startup procedures with thread affinity and so on. The freeze happens without fail when I enable this mod. I wonder if there's anything more to this, but my Forge knowledge is fairly limited and reading code will only tell me so much.

**Comment by GAsplund** [comment]
Another update, I took a thread dump when VisualVM detected a threadlock. I thought it may give more clues since it actually states the line numbers rather than just calls.

```
"Render thread" #1 prio=10 os_prio=2 cpu=693953.12ms elapsed=3988.96s tid=0x000002284e6cb200 nid=0x49b8 waiting for monitor entry  [0x00000051a46fc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at journeymap.client.data.DataCache.getPlayer(DataCache.java:334)
        - waiting to lock <0x000000067d74fb80> (a com.google.common.cache.LocalCache$LocalLoadingCache)
        at journeymap.client.data.DataCache.getPlayer(DataCache.java:207)
        at journeymap.client.model.MapState.shouldRefresh(MapState.java:578)
        at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:224)
        at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:198)
        at journeymap.client.ui.UIManager.drawMiniMap(UIManager.java:338)
        at journeymap.client.forge.event.MiniMapOverlayHandler.onRenderOverlay(MiniMapOverlayHandler.java:102)
        at net.minecraftforge.eventbus.ASMEventHandler_3222_MiniMapOverlayHandler_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus$$Lambda$3776/0x0000000801677958.invoke(Unknown Source)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:828)
        at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:121)
        at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:765)
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
        at net.minecraft.client.main.Main.main(Main.java:184)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@15/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@15/NativeMethodAccessorImpl.java:64)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@15/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@15/Unknown Source)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$680/0x0000000800f6e2d8.call(Unknown Source)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@15/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@15/NativeMethodAccessorImpl.java:64)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@15/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@15/Unknown Source)
        at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:53)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@15/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@15/NativeMethodAccessorImpl.java:64)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@15/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@15/Unknown Source)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(Unknown Source)
        at org.multimc.onesix.OneSixLauncher.launch(Unknown Source)
        at org.multimc.EntryPoint.listen(Unknown Source)
        at org.multimc.EntryPoint.main(Unknown Source)
```

**Comment by mysticdrew** [comment]
I have been unable to replicate this issue. 
I tried in my development and production environment forge: 36.2.22 and SmoothBoot: 1.16.4-1.2.2
I have not added Optifine yet, I will test that installed in my production environment later and report back.

**Comment by GAsplund** [comment]
Alright. I suspect that Smooth Boot is not the issue. I did have a freeze yesterday (albeit much later) after removing Smooth Boot. Do you know of a good way of manually triggering `MapState.shouldRefresh`? It would make it significantly easier for me to test if a combination is "faulty" or not.

**Comment by GAsplund** [comment]
Alright, I've joined. Handle is `GAsplund#1337` for when you return.

**Comment by GAsplund** [comment]
We were unable to solve the issue. The freeze only seemed to be reproducible on my side at random, and @mysticdrew was not able to reproduce it on his side at all, no matter how much we tried to create the same circumstances as I had. The former made it nearly impossible for me to test which mod caused the issue, and lead to many false positives. 

The assumption is that another mod is causing a lockup in the `JM-Task` thread while trying to access some entity data, which in turn locks up on waiting for a `ReentrantReadWriteLock` to unlock (which it never does). Since `getPlayer()` is locked further up in the call stack and never gets released, a deadlock is created when anything tries to call `getPlayer()`. This leads to an immediate freeze when for example `shouldRefresh` is called in the render thread, which is where this main issue stems from.

For any future reference, I have included deadlock info from a thread dump:
```
Found one Java-level deadlock:
=============================
"JM-task-4":
  waiting for ownable synchronizer 0x000000063459d130, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "Render thread"
"Render thread":
  waiting to lock monitor 0x000001b66e1f81b8 (object 0x000000063ece8568, a com.google.common.cache.LocalCache$LocalLoadingCache),
  which is held by "JM-task-4"

Java stack information for the threads listed above:
===================================================
"JM-task-4":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000063459d130> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(Unknown Source)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(Unknown Source)
        at net.minecraft.network.datasync.EntityDataManager.func_187219_c(EntityDataManager.java:137)
        at net.minecraft.network.datasync.EntityDataManager.func_187225_a(EntityDataManager.java:161)
        at net.minecraft.entity.Entity.func_70083_f(Entity.java:1949)
        at net.minecraft.entity.Entity.func_82150_aj(Entity.java:1918)
        at net.minecraft.entity.Entity.func_98034_c(Entity.java:1927)
        at journeymap.client.model.EntityDTO.update(EntityDTO.java:165)
        at journeymap.client.data.PlayerData.load(PlayerData.java:88)
        at journeymap.client.data.PlayerData.load(PlayerData.java:27)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
        - locked <0x000000075e132480> (a com.google.common.cache.LocalCache$StrongWriteEntry)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
        at journeymap.client.data.DataCache.getPlayer(DataCache.java:342)
        - locked <0x000000063ece8568> (a com.google.common.cache.LocalCache$LocalLoadingCache)
        at journeymap.client.data.DataCache.getPlayer(DataCache.java:207)
        at journeymap.client.task.multi.RenderSpec.getTopoSpec(RenderSpec.java:168)
        at journeymap.client.task.multi.MapPlayerTask.initTask(MapPlayerTask.java:263)
        at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:67)
        at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72)
        at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:423)
        at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
"Render thread":
        at journeymap.client.data.DataCache.getPlayer(DataCache.java:334)
        - waiting to lock <0x000000063ece8568> (a com.google.common.cache.LocalCache$LocalLoadingCache)
        at journeymap.client.data.DataCache.getPlayer(DataCache.java:207)
        at journeymap.client.model.MapState.shouldRefresh(MapState.java:578)
        at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:224)
        at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:198)
        at journeymap.client.ui.UIManager.drawMiniMap(UIManager.java:338)
        at journeymap.client.forge.event.MiniMapOverlayHandler.onRenderOverlay(MiniMapOverlayHandler.java:102)
        at net.minecraftforge.eventbus.ASMEventHandler_3215_MiniMapOverlayHandler_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus$$Lambda$3607/295203971.invoke(Unknown Source)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:828)
        at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:121)
        at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:765)
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
        at net.minecraft.client.main.Main.main(Main.java:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$519/716154959.call(Unknown Source)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
        at org.multimc.EntryPoint.listen(EntryPoint.java:143)
        at org.multimc.EntryPoint.main(EntryPoint.java:34)

Found 1 deadlock.
```
