### ISSUE TITLE
[1.12.2] Repeating NPE (thousands of times) while painting contour

### ISSUE THREAD

**Issue by Geethebluesky** [TeamJM/journeymap#38]
#### Forge Version: *forge-1.12.2-14.23.2.2654*
(Using this version because Foamfix 0.9.6 requires at least 2651)

#### Describe the problem in repeatable steps:

I have been able to play with Journeymap on the setup described above (forge 2654, journeymap 5.5.2) for ~2 days, but as I've started exploring more of my map, which is pregenerated on a separate PC server, the game has started 1. eating up incredible amounts of memory shortly after logging in (it wants to go past 12 Gb... I only have 16 total), 2. crashing to desktop within seconds of logging in.

The memory problem is the main issue I'm attempting to diagnose--while doing that, I, saw the following happening with Journeymap in the logs, thought it may be related, if not the cause of the crash, but I can't tell if it is.

Here is the log section where journeymap starts to load... (everything's normal here)

`[19:23:50] [main/INFO] [journeymap]: Loading journeymap.topo.config
[19:23:50] [main/INFO] [journeymap]: Custom modded block handling enabled for biomesoplenty
[19:23:50] [main/INFO] [journeymap]: Loaded 18 waypoints from c:\Users\Gen\AppData\Roaming\.minecraft_1.12.2\journeymap\data\mp\Zakalwe\waypoints
[19:23:50] [main/INFO] [journeymap]: Mapping started in c:\Users\Gen\AppData\Roaming\.minecraft_1.12.2\journeymap\data\mp\Zakalwe\DIM0. Memory: 2684MB total, 1060MB free 
[19:23:50] [main/WARN] [journeymap]: Image not found: quark:textures/entity_icon/random/pig1.png
[19:23:50] [main/WARN] [journeymap]: Image not found: quark:textures/entity_icon/random/pig2.png
[19:23:50] [main/WARN] [journeymap]: Image not found: quark:textures/entity_icon/random/pig3.png
[19:23:50] [main/WARN] [journeymap]: Image not found: quark:textures/entity_icon/random/pig4.png`

Next, **latest.log** and **debug.log** on the client fill up full of the error pasted below. The server (on a different PC) keeps running and shows no errors whatsoever (neither in latest.log or debug.log).

The repeating error follows; when I say _repeating_ I mean that both logs show tens of thousands of lines of the same error repeating 1000s of times. 

I have removed the line timestamps to make the actual traceback more legible. [Intact paste here](https://pastebin.com/4DbjeUE3).

` java.lang.NullPointerException
 	at journeymap.client.cartography.render.TopoRenderer.paintContour(TopoRenderer.java:396)
 	at journeymap.client.cartography.render.TopoRenderer.renderSurface(TopoRenderer.java:186)
 	at journeymap.client.cartography.render.TopoRenderer.render(TopoRenderer.java:138)
 	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:133)
 	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:125)
 	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:75)
 	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:416)
 	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:81)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
 	at java.util.concurrent.FutureTask.run(Unknown Source)
 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 	at java.lang.Thread.run(Unknown Source)`

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

I cannot tell if anything relevant is in the log, however please find the complete journeymap.log written to until the NPE [here](https://pastebin.com/eri1XdmG). journeymap.log seems to cut off exactly the second after the NPE series starts.

Edit: Here's the [Minecraft crash log](https://pastebin.com/SavfsvzL) (hs_err_pidxxxx.log)

**Comment by mysticdrew** [comment]
Is this still happening with version 5.5.4?

**Comment by mysticdrew** [comment]
Closing, if this is still an issue when we get a response I will reopen.
