### ISSUE TITLE
[1.16.5-1.18.1] Failed to load waypoint that created from API and saved with custom icon 

### ISSUE THREAD

**Issue by frank89722** [TeamJM/journeymap#382]
#### JourneyMap Version:

`1.18.1-5.8.0beta10` (Starting to happen since beta8)

#### Forge Version:

`39.0.59`

#### Describe the problem in repeatable steps:

1. Create a waypoint with an icon through JM API (everything still works)
2. Relaunch the game and enter the world which is saved with the waypoint that has been created in step one. 
3. Client render broke. 

And it is also unable to create waypoints without a custom Icon after 5.8.0beta8
[Here is how I create waypoints](https://github.com/frank89722/JourneyMapIntegration/blob/f4506103ce3de14533bd79124c99fd741fff5483/src/main/java/frankv/jmi/waystones/client/WaystoneMarkerListener.java#L44)
For custom icon I just add `waypoint.setIcon(overlay.getIcon());` under line 45 

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

- Try to create a waypoint without a custom Icon:
```
[17:27:49] [Render thread/ERROR]: [ClientAPI] Error showing displayable: Waypoint{name=vd, dim=minecraft:overworld, pos=BlockPos{x=2, y=126, z=-6}, group=null, icon=null, color=null, bgColor=null, displayDims=[minecraft:overworld], editable=true, persistent=true, dirty=true}
java.lang.NullPointerException: Cannot invoke "journeymap.client.api.model.MapImage.getImageLocation()" because the return value of "journeymap.client.api.display.Waypoint.getIcon()" is null
	at journeymap.client.api.impl.PluginWrapper.show(PluginWrapper.java:117) ~[journeymap-32274-3612223_mapped_official_1.18.1.jar%2389!/:1.18.1-5.8.0beta10]
	at journeymap.client.api.impl.ClientAPI.show(ClientAPI.java:121) ~[journeymap-32274-3612223_mapped_official_1.18.1.jar%2389!/:1.18.1-5.8.0beta10]
	at frankv.jmi.waystones.client.WaystoneMarkerListener.onMouseClick(WaystoneMarkerListener.java:48) ~[%2381!/:?]
	at journeymap.client.ui.fullscreen.layer.ModOverlayLayer.fireOnMouseClick(ModOverlayLayer.java:280) ~[journeymap-32274-3612223_mapped_official_1.18.1.jar%2389!/:1.18.1-5.8.0beta10]
	at journeymap.client.ui.fullscreen.layer.ModOverlayLayer.onMouseClick(ModOverlayLayer.java:117) ~[journeymap-32274-3612223_mapped_official_1.18.1.jar%2389!/:1.18.1-5.8.0beta10]
	at journeymap.client.ui.fullscreen.layer.LayerDelegate.onMouseClicked(LayerDelegate.java:105) ~[journeymap-32274-3612223_mapped_official_1.18.1.jar%2389!/:1.18.1-5.8.0beta10]
	at journeymap.client.ui.fullscreen.Fullscreen.mouseClicked(Fullscreen.java:1071) ~[journeymap-32274-3612223_mapped_official_1.18.1.jar%2389!/:1.18.1-5.8.0beta10]
	at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:88) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.gui.screens.Screen.wrapScreenError(Screen.java:527) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.MouseHandler.onPress(MouseHandler.java:85) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.MouseHandler.lambda$setup$4(MouseHandler.java:185) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:90) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.MouseHandler.lambda$setup$5(MouseHandler.java:184) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2355!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2361!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2355!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:162) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at com.mojang.blaze3d.platform.Window.updateDisplay(Window.java:333) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1062) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:660) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[forge-1.18.1-39.0.59_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38) ~[fmlloader-1.18.1-39.0.59.jar%230!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%2310!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%2310!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%2310!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%2310!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%2310!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%2310!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%2310!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

- Login to the world that saved with custom Icon:
```
[17:32:04] [Render thread/ERROR]: Error during MiniMap.drawMap(): Cannot invoke "journeymap.client.render.texture.TextureImpl.getWidth()" because "this.texture" is null (SUPPRESSED)
[17:32:04] [Render thread/ERROR]: java.lang.NullPointerException: Cannot invoke "journeymap.client.render.texture.TextureImpl.getWidth()" because "this.texture" is null
	at TRANSFORMER/journeymap@5.8.0beta10/journeymap.client.render.draw.DrawWayPointStep.draw(DrawWayPointStep.java:102)
	at TRANSFORMER/journeymap@5.8.0beta10/journeymap.client.ui.minimap.MiniMap.drawOnMapWaypoints(MiniMap.java:478)
	at TRANSFORMER/journeymap@5.8.0beta10/journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:330)
	at TRANSFORMER/journeymap@5.8.0beta10/journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:199)
	at TRANSFORMER/journeymap@5.8.0beta10/journeymap.client.ui.UIManager.drawMiniMap(UIManager.java:338)
	at TRANSFORMER/journeymap@5.8.0beta10/journeymap.client.forge.event.MiniMapOverlayHandler.onRenderOverlay(MiniMapOverlayHandler.java:102)
	at net.minecraftforge.eventbus.ASMEventHandler_149_MiniMapOverlayHandler_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.7/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.7/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.7/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.59/net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:876)
	at TRANSFORMER/forge@39.0.59/net.minecraftforge.client.gui.ForgeIngameGui.render(ForgeIngameGui.java:351)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:866)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1040)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.run(Minecraft.java:660)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

```

**Comment by mysticdrew** [comment]
fixed in beta11, published to curseforge though not approved at the time of closing this issue
