### ISSUE TITLE
[1.18.1] Error rendering surface when Tinkers Construct 1.18 is added to modpack

### ISSUE THREAD

**Issue by Jessman5** [TeamJM/journeymap#391]
#### JourneyMap Version:

5.8.0beta12

#### Forge Version:

39.0.64

#### Describe the problem in repeatable steps:

Journeymap is continuously throwing following warning in the console and in the log file

`[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.cartography.render.SurfaceRenderer.paintStrata(SurfaceRenderer.java:437)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.cartography.render.SurfaceRenderer.renderSurface(SurfaceRenderer.java:220)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:122)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:92)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:154)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:123)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:423)
[03/02/2022 19:31:39 PM] 	at TRANSFORMER/journeymap@5.8.0beta12/journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:77)
[03/02/2022 19:31:39 PM] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[03/02/2022 19:31:39 PM] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[03/02/2022 19:31:39 PM] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[03/02/2022 19:31:39 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03/02/2022 19:31:39 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03/02/2022 19:31:39 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[03/02/2022 19:31:39 PM] [JM-task-3/WARN] Error rendering surface: `

**Comment by Jessman5** [comment]
Okay to I tried sth. I added Tinkers Construct 1.18 today and it seems that the error occurs, when this mod is added. It doesn't occur when I remove/disable the mod. I don't know if this is TC related or JM related or both, so I will put that issue also in their Repo.
I have attached the log files you've asked for. Also two screenshots where JM seems to have issues with sand and stuff when TC is added.

[journeymap.log](https://github.com/TeamJM/journeymap/files/7997499/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/7997501/latest.log)
<img width="983" alt="Bildschirmfoto 2022-02-03 um 20 20 06" src="https://user-images.githubusercontent.com/4819469/152413779-91509e13-41cf-46d1-a026-a165682d41a5.png">
<img width="1135" alt="Bildschirmfoto 2022-02-03 um 20 20 21" src="https://user-images.githubusercontent.com/4819469/152413798-20c81517-e793-415b-b1e7-48578ec48865.png">

**Comment by mysticdrew** [comment]
thanks, looks like a corrupt chunk.
Have you tried running the optimize world and clearing the cache? From the world selection screen, select your world, hit edit.

**Comment by Jessman5** [comment]
I did further testing:
JM + Optifine = all good
JM + Optifine + TC = messed up
JM + TC = map looks like the messed up screen first but gets to normal after a second.

So I guess it's rather an issue with TC + Optifine that messes up the JM second handedly.

Sorry for the inconvenience. 
I'd like to link this conversation to the TC issue.
