### ISSUE TITLE
[1.12.2] Teleporting fails in single player

### ISSUE THREAD

**Issue by Alpvax** [TeamJM/journeymap#40]
#### JourneyMap Version:

`1.12.2-5.6.0b2` (Was in a modpack, will downgrade and re-test)

#### Forge Version:

`1.12.1-14.23.1.2590`

#### Describe the problem in repeatable steps:

1. Enable teleporting to waypoints in config
2. Load single player world
3. Attempt to teleport to a waypoint

Forge crash log: (also in journeymap log)
`[08:09:32] [Server thread/WARN]: Force-added player with duplicate UUID 84d45dc0-84f8-47ca-b128-26c4118d92a8
[08:09:32] [Server thread/ERROR] [journeymap]: Error with CommandJTP: java.lang.ClassCastException: net.minecraft.client.multiplayer.WorldClient cannot be cast to net.minecraft.world.WorldServer
	at journeymap.common.action.JourneyMapTeleport.teleportEntity(JourneyMapTeleport.java:134)
	at journeymap.common.action.JourneyMapTeleport.attemptTeleport(JourneyMapTeleport.java:109)
	at journeymap.common.command.CommandJTP.func_184881_a(CommandJTP.java:53)
[08:09:32] [main/INFO]: [CHAT] /jtp failed Usage: /jtp <x y z dim>`

**Comment by Alpvax** [comment]
After downgrading, the issue no longer occurred.
