### ISSUE TITLE
Does not allow to the server due to an error in the console.

### ISSUE THREAD

**Issue by SadnessOfficial** [TeamJM/journeymap#445]
[18:43:89] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot read field "dimension" because "this.mapType" is null
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.render.map.GridRenderer.updateUIState(GridRenderer.java:696)
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.ui.minimap.MiniMap.updateUIState(MiniMap.java:123)
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.ui.minimap.MiniMap.updateDisplayVars(MiniMap.java:823)
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.ui.minimap.MiniMap.reset(MiniMap.java:729)
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.JourneymapClient.reset(JourneymapClient.java:613)
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.JourneymapClient.startMapping(JourneymapClient.java:521)
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:78)
[18:43:89] [Render thread/INFO]: [STDERR]: 	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:83)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:634)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at journeymap.client.event.handlers.StateTickHandler.onClientTick(StateTickHandler.java:54)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at journeymap.client.event.fabric.FabricEventHandlerManager.lambda$registerFabricEvents$0(FabricEventHandlerManager.java:58)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$zfe000$onEndTick(class_310.java:5472)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1817)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1091)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[18:43:90] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:43:90] [Render thread/ERROR]: Error in JourneyMap.performMainThreadTasks(): java.lang.NullPointerException: Cannot invoke "journeymap.client.api.util.UIState.equals(Object)" because "newState" is null
	at journeymap.client.render.map.GridRenderer.updateUIState(GridRenderer.java:711)
	at journeymap.client.ui.minimap.MiniMap.updateUIState(MiniMap.java:123)
	at journeymap.client.ui.minimap.MiniMap.updateDisplayVars(MiniMap.java:823)
	at journeymap.client.ui.minimap.MiniMap.reset(MiniMap.java:729)
	at journeymap.client.JourneymapClient.reset(JourneymapClient.java:613)
	at journeymap.client.JourneymapClient.startMapping(JourneymapClient.java:521)
	at journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:78)
	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:83)
	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:634)
	at journeymap.client.event.handlers.StateTickHandler.onClientTick(StateTickHandler.java:54)
	at journeymap.client.event.fabric.FabricEventHandlerManager.lambda$registerFabricEvents$0(FabricEventHandlerManager.java:58)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zfe000$onEndTick(class_310.java:5472)
	at net.minecraft.class_310.method_1574(class_310.java:1817)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
# After that, there is a copy of the error in the console, and so on ad infinitum.

**Comment by mysticdrew** [comment]
follow the template.
