### ISSUE TITLE
[1.12.2] Various logspam messages

### ISSUE THREAD

**Issue by C0rn3j** [TeamJM/journeymap#49]
Files:
```
journeymap-1.12.2-5.5.2.jar
jei_1.12.2-4.9.1.187.jar
forge-1.12.2-14.23.3.2702-universal.jar
```
Full log: 
https://haste.rys.pw/raw/cuvuwekece

- [ ] Theme problem

```
[23:32:41] [main/ERROR] [journeymap]: Default theme not found in /home/c0rn3j/.local/share/multimc/instances/1.12.2 debug/.minecraft/journeymap/icon/theme/flat/OceanMonument.theme2.json: OceanMonument (SUPPRESSED)
[23:32:41] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[23:32:41] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
```

- [ ] Icon problem
```
[23:32:42] [main/ERROR] [journeymap]: Couldn't locate icons for Default: /home/c0rn3j/.local/share/multimc/instances/1.12.2%20debug/.minecraft/mods/journeymap-1.12.2-5.5.2.jar/assets/journeymap/icon/entity
[23:32:42] [main/INFO] [journeymap]: Added entity icons from journeymap:icon/entity. Success: false
[23:32:42] [main/ERROR] [journeymap]: Couldn't locate icons for flat: /home/c0rn3j/.local/share/multimc/instances/1.12.2%20debug/.minecraft/mods/journeymap-1.12.2-5.5.2.jar/assets/journeymap/theme/flat
```

- [ ] Version checking problem

```
[23:32:42] [JM-VersionCheck-1/ERROR] [journeymap]: Could not check version URL
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:134) [VersionCheck$1.class:1.12.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
	... 7 more
```

if either or both of the first two issues are just normal messages, they shouldn't ERR/WARN but post as INFO.

**Comment by C0rn3j** [comment]
Re-test.
```
Launcher: multimc 0.6.2.r33.ga279df8b as

journeymap-1.12.2-5.5.2
forge-1.12.2-14.23.4.2758
```

Full log: https://haste.rys.pw/uyufixebuq.md

in addition to the still-present initially reported issues, there's now more.

World create/load:

```
[16:35:24] [Server thread/ERROR] [journeymap]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[16:35:24] [Server thread/ERROR] [journeymap]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[16:35:24] [Server thread/INFO] [FML]: Unloading dimension -1
[16:35:24] [Server thread/ERROR] [journeymap]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[16:35:24] [Server thread/ERROR] [journeymap]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```


When opening up the map with J for the first time:
```
[16:35:35] [JM-texture-3/WARN] [journeymap]: Couldn't get a skin at all for techbrew
[16:35:35] [JM-texture-2/WARN] [journeymap]: Couldn't get a skin at all for mysticdrew
[16:35:36] [JM-texture-3/WARN] [journeymap]: Couldn't get a skin at all for AlexDurrani
[16:35:36] [JM-texture-2/WARN] [journeymap]: Couldn't get a skin at all for Davkas
[16:35:36] [JM-texture-3/WARN] [journeymap]: Couldn't get a skin at all for TECH_GEEK10
[16:35:36] [JM-texture-2/WARN] [journeymap]: Couldn't get a skin at all for _TheEndless_
[16:35:36] [JM-texture-3/WARN] [journeymap]: Couldn't get a skin at all for eladjenkins
```

**Comment by mysticdrew** [comment]
not an issue.

**Comment by C0rn3j** [comment]
if it's not an issue it should be giving INFO/WARN messages, not ERROR

**Comment by mysticdrew** [comment]
I've addressed this in several other issue topics. I will be cleaning this up.
