### ISSUE TITLE
[1.18.2] Crash on beta2 Forge on launch

### ISSUE THREAD

**Issue by itsdinkd** [TeamJM/journeymap#505]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Upload your log files or use gist, pastebin, or some similar site. Pasting log contents directly into the issue will get the issue closed immediately.
5. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
6. #### Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`5.9.0beta2`

#### Forge Version:

`40.1.80`

#### Describe the problem in repeatable steps:

1. Updated to Beta2
2. Set loader to 40.1.80
3. use on my modpack, Another quality modpack 3
4. Launch and crash after game loads

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

journeymap.log doesn't generate

**Crash log**
https://pastebin.com/VpdYR23y

**latest.log**
```java
27Sep2022 13:55:50.840] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: journeymap, class journeymap.common.Journeymap
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.80.jar%23408!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.80.jar%23407!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.AssertionError: REI Internals have not been initialized!
	at me.shedaniel.rei.impl.ClientInternals.throwNotSetup(ClientInternals.java:82) ~[RoughlyEnoughItems-8.3.545.jar%23327!/:?]
	at me.shedaniel.rei.impl.ClientInternals.getPluginManager(ClientInternals.java:163) ~[RoughlyEnoughItems-8.3.545.jar%23327!/:?]
	at me.shedaniel.rei.api.common.plugins.PluginManager.getClientInstance(PluginManager.java:46) ~[RoughlyEnoughItems-8.3.545.jar%23327!/:?]
	at me.shedaniel.rei.api.client.config.ConfigManager.getInstance(ConfigManager.java:40) ~[RoughlyEnoughItems-8.3.545.jar%23327!/:?]
	at me.shedaniel.rei.api.client.config.ConfigObject.getInstance(ConfigObject.java:45) ~[RoughlyEnoughItems-8.3.545.jar%23327!/:?]
	at com.mojang.blaze3d.platform.InputConstants.isPatchingAsyncThreadCrash(InputConstants.java:593) ~[client-1.18.2-20220404.173914-srg.jar%23406!/:?]
	at com.mojang.blaze3d.platform.InputConstants.handler$cig000$isKeyDown(InputConstants.java:586) ~[client-1.18.2-20220404.173914-srg.jar%23406!/:?]
	at com.mojang.blaze3d.platform.InputConstants.m_84830_(InputConstants.java) ~[client-1.18.2-20220404.173914-srg.jar%23406!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96637_(Screen.java:494) ~[client-1.18.2-20220404.173914-srg.jar%23406!/:?]
	at journeymap.client.event.handlers.keymapping.KeyModifier.<clinit>(KeyModifier.java:7) ~[journeymap-1.18.2-5.9.0beta2-forge.jar%23225!/:1.18.2-5.9.0beta2]
	at journeymap.client.event.handlers.KeyEventHandler.<init>(KeyEventHandler.java:159) ~[journeymap-1.18.2-5.9.0beta2-forge.jar%23225!/:1.18.2-5.9.0beta2]
	at journeymap.client.event.forge.ForgeKeyEvents.<init>(ForgeKeyEvents.java:34) ~[journeymap-1.18.2-5.9.0beta2-forge.jar%23225!/:1.18.2-5.9.0beta2]
	at journeymap.client.JourneymapClient.<init>(JourneymapClient.java:117) ~[journeymap-1.18.2-5.9.0beta2-forge.jar%23225!/:1.18.2-5.9.0beta2]
	at journeymap.common.Journeymap.lambda$new$0(Journeymap.java:110) ~[journeymap-1.18.2-5.9.0beta2-forge.jar%23225!/:1.18.2-5.9.0beta2]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.18.2-40.1.80.jar%23407!/:?]
	at journeymap.common.Journeymap.<init>(Journeymap.java:110) ~[journeymap-1.18.2-5.9.0beta2-forge.jar%23225!/:1.18.2-5.9.0beta2]
	... 14 more
```

**Comment by itsdinkd** [comment]
also tried 40.1.79, same crash

**Comment by mysticdrew** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/1134
https://github.com/shedaniel/RoughlyEnoughItems/issues/1136

Looks like an issue with the latest REI. Roll it back to an older version according to these issues.

**Comment by itsdinkd** [comment]
I tried 40.1.70 though and it works fine.

**Comment by mysticdrew** [comment]
Looks like due to a breaking change with forge 40.1.80. Not sure if this is a JM or REI issue. I will look into it on my end.

**Comment by itsdinkd** [comment]
just kidding i lied it did not load on .70

**Comment by mysticdrew** [comment]
I added a fix, it will be in beta3 when ever I get time to release it. Still some other bugs preventing release.

**Comment by mysticdrew** [comment]
This now also fixed on REI's end.
