### ISSUE TITLE
[1.12.2] Certain waypoint names crash the game

### ISSUE THREAD

**Issue by tilda** [TeamJM/journeymap#53]
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.3.2702

#### Describe the problem in repeatable steps:

1. Make a waypoint
2. Name it something like "??? test"
3. Try to click "Chat" and press enter
4. Watch the game crash.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Nothing in there. However I do have a MC crash report that shows the error.
```
[19:49:44] [main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1770) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 3
"??? house"
   ^
	at java.util.regex.Pattern.error(Pattern.java:1957) ~[?:1.8.0_171]
	at java.util.regex.Pattern.sequence(Pattern.java:2125) ~[?:1.8.0_171]
	at java.util.regex.Pattern.expr(Pattern.java:1998) ~[?:1.8.0_171]
	at java.util.regex.Pattern.compile(Pattern.java:1698) ~[?:1.8.0_171]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_171]
	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_171]
	at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_171]
	at journeymap.client.waypoint.WaypointParser.parse(WaypointParser.java:111) ~[WaypointParser.class:1.12.2-5.5.2]
	at journeymap.client.model.Waypoint.toChatString(Waypoint.java:869) ~[Waypoint.class:1.12.2-5.5.2]
	at journeymap.client.model.Waypoint.toChatString(Waypoint.java:838) ~[Waypoint.class:1.12.2-5.5.2]
	at journeymap.client.ui.waypoint.WaypointChat.<init>(WaypointChat.java:13) ~[WaypointChat.class:1.12.2-5.5.2]
	at journeymap.client.ui.waypoint.WaypointManagerItem.clickScrollable(WaypointManagerItem.java:237) ~[WaypointManagerItem.class:1.12.2-5.5.2]
	at journeymap.client.ui.waypoint.WaypointManagerItem.func_148278_a(WaypointManagerItem.java:353) ~[WaypointManagerItem.class:1.12.2-5.5.2]
	at journeymap.client.ui.component.ScrollListPane.func_148179_a(ScrollListPane.java:172) ~[ScrollListPane.class:1.12.2-5.5.2]
	at journeymap.client.ui.waypoint.WaypointManager.func_73864_a(WaypointManager.java:302) ~[WaypointManager.class:1.12.2-5.5.2]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) ~[blk.class:?]
	at journeymap.client.ui.waypoint.WaypointManager.func_146274_d(WaypointManager.java:335) ~[WaypointManager.class:1.12.2-5.5.2]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757) ~[bib.class:?]
	... 17 more
```

**Comment by iggy12345** [comment]
This occurs when you try to chat the waypoint to other players

**Comment by tilda** [comment]
Yeah, that was something I forgot to include. Adding to issue.

**Comment by mysticdrew** [comment]
Fixed for release of 5.5.5

**Comment by iggy12345** [comment]
Woot! It's getting fixed!

**Comment by tilda** [comment]
:tada:
