### ISSUE TITLE
[1.12.2] Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission

### ISSUE THREAD

**Issue by BrainStone** [TeamJM/journeymap#54]
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.4.2705

#### Describe the problem in repeatable steps:

The following exception gets thrown when I updated to the current recommended Forge build and a player connects to the server.

#### Error log:

```
> [10:09:03] [Server thread/INFO] [journeymap]: The_BrainStone joining dimension 0
> [10:09:03] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_32_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) [EventBus.class:?]
at org.spongepowered.common.SpongeImplHooks.firePlayerJoinSpawnEvent(SpongeImplHooks.java:677) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3149]
at org.spongepowered.common.event.tracking.PhaseTracker.spawnEntity(PhaseTracker.java:661) [PhaseTracker.class:1.12.2-2705-7.1.0-BETA-3149]
at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:2688) [oo.class:?]
at net.minecraft.server.management.PlayerList.handler$playerLoggedIn2$zjh000(PlayerList.java:2044) [pl.class:?]
at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:367) [pl.class:?]
at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1583) [pl.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
... 30 more
```

**Comment by Weissmoon** [comment]
Same as #42.
