### ISSUE TITLE
[1.12.2] NPE at WorldEventHandler.onUnload

### ISSUE THREAD

**Issue by NightKosh** [TeamJM/journeymap#56]
#### JourneyMap Version:
1.12.2-5.5.2

#### Forge Version:
1.12.2-v14.23.4.2705

```
[19:27:21] [Server thread/ERROR]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_911_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[19:27:21] [Server thread/ERROR]: Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_911_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by MechanosG** [comment]
I'm having this same problem I think.  Wasn't sure if Journeymap was the cause, but it's definitely mentioned in the log.  It's happening to me in a new modpack, when I try to create a new singleplayer world, and preventing loading into the new world, kicking me to the server list.  Probably 25% of the time, I'm able to create a world without this happening though.
`[20:48:45] [Server thread/ERROR] [journeymap]: ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1955_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more`

**Comment by MechanosG** [comment]
Even if you turn off your Google data collection, it's still causing failures to load game worlds.  Even existing worlds.  The Google affiliation was already bad enough.  But now it's _possibly_ breaking my modpack?  I understand (from reddit posts) that you feel much more motivated to work on the mod, when you're able to track what your users are playing on and where.  But I don't see any logical reason for Google code to still be being ran, when joining a singleplayer map, with both MC snooper turned off, and modinfo config in journeymap set to false.  It's too suspicious, even if you do fix whatever bug is messing up things.  Giving Google more telemetry is never a good thing anyway, but that's straying off topic.

For anyone else having this same problem, I'll be trying out Xaero's Minimap and World Map, to see if I'm able to load worlds again.

**Comment by tupperkion** [comment]
Same issue here. Happened when I upgraded my modpack from 1.10.2 to 1.12.2. Can't load my survival world. This would cause the game to hang on "Loading world... building terrain". Full log below.

### [`latest.log`](https://gist.github.com/tupperkion/d0eee6c263fb85e8a01ae9f35feea451)

**Comment by darkrider0** [comment]
Same issue. This time it happened after joining a multiplayer server, leaving, and then loading up my singleplayer world. When I restart my client then I can run my singleplayer world without problem.
Running FTB Continuum + Wall Jump + Sound Filters.

[2018-09-08-2.log](https://github.com/TeamJM/journeymap/files/2363830/2018-09-08-2.log)

**Comment by EngineerXL** [comment]
This error occurs more often with JourneyMap 5.5.3

**Comment by mysticdrew** [comment]
This is not a bug, maybe too many logs. Before stopping mapping we verify that the player dimension is the world dimension, then we stop. But, if the world has stopped, minecraft sets the world to null, so when we do a check on, it is null and throws an exception. This should not effect anything other than maybe a few too many logs.
