### ISSUE TITLE
[Bug]: New mp directory is created for same server, every login

### ISSUE THREAD

**Issue by AzyxA** [TeamJM/journeymap#573]
### What happened?

I just started using journeymap and I only play on one server.   Every time start up Minecraft and join the server, journeymap will create a new directory under \journeymap\data\mp thus losing my previous mapping progress. 
I end up having to copy all the files from older mp folders to the newly created folder.  Not optimal. 

I have seen this question asked a couple times on some forums but with no resolution. 

Any way to solve this?

### Minecraft Version

1.19.3+(Default)

### Version

5.9.3 (Default)

**Comment by mysticdrew** [comment]
What forums, and provide logs

**Comment by mysticdrew** [comment]
Without providing logs or any more details about the issue, I cannot really do much. What has it remaining the folders to? 

Can you provide a screenshot of your mp folder shoo I can see the names. 

How are you connecting to the server within Minecraft?

**Comment by AzyxA** [comment]
Sorry for the delay. 


Here is a snippet of the log where it resets the UID prefix to the server name, creating a new folder called \FinalScore_id_~4096083208109196453 and thus, upon logging back in, my map progress is in the old \FinalScore_id_2609148662475084659 folder


[23:09:04] [Render thread/INFO] [JourneymapClient] Mapping halted in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\minecraft:outworld_nether
[23:09:05] [Render thread/INFO] [WaypointStore] Loaded 11 waypoints from C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\waypoints
[23:09:05] [Render thread/INFO] [JourneymapClient] Mapping started in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\outworld. Memory: 1824MB total, 732MB free 
[23:09:58] [Render thread/INFO] [JourneymapClient] Mapping halted in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\minecraft:outworld
[23:09:59] [Render thread/INFO] [WaypointStore] Loaded 11 waypoints from C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\waypoints
[23:09:59] [Render thread/INFO] [JourneymapClient] Mapping started in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\outworld_nether. Memory: 1824MB total, 557MB free 
[23:12:13] [Render thread/INFO] [JourneymapClient] Mapping halted in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\minecraft:outworld_nether
[23:12:14] [Render thread/INFO] [WaypointStore] Loaded 11 waypoints from C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\waypoints
[23:12:14] [Render thread/INFO] [JourneymapClient] Mapping started in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\outworld. Memory: 1824MB total, 860MB free 
[23:14:43] [Render thread/INFO] [JourneymapClient] Mapping halted in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\minecraft:outworld
[23:14:44] [Render thread/INFO] [WaypointStore] Loaded 11 waypoints from C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\waypoints
[23:14:44] [Render thread/INFO] [JourneymapClient] Mapping started in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\psi. Memory: 1824MB total, 686MB free 
[23:14:49] [JM-task-53/WARN] [SurfaceRenderer] Error rendering surface: 
journeymap.client.model.ChunkMD$ChunkMissingException: Chunk missing: [-4, 4]
	at journeymap.client.model.ChunkMD.getChunk(ChunkMD.java:406) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.model.ChunkMD.getBiome(ChunkMD.java:162) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.cartography.render.SurfaceRenderer.renderSurface(SurfaceRenderer.java:222) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:123) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:93) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:169) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:125) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:424) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:77) ~[journeymap-1.19.3-5.9.3-forge.jar%23149!/:1.19.3-5.9.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:17:34] [Render thread/INFO] [JourneymapClient] Mapping halted in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_2609148662475084659\minecraft:psi
[23:17:35] [Render thread/INFO] [MappingMonitorTask] World ID has been reset.
[23:17:35] [Render thread/INFO] [JourneymapClient] World UID is set to: null
[23:17:48] [Netty Client IO #3/INFO] [ForgeConfig] Loading JourneyMap Forge Configs
[23:17:48] [Render thread/INFO] [JourneymapClient] World UID is set to: id_-4096083208109196453
[23:17:49] [Render thread/INFO] [WaypointStore] Loaded 0 waypoints from C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_~4096083208109196453\waypoints
[23:17:49] [Render thread/INFO] [JourneymapClient] Mapping started in C:\Users\AzyxA\AppData\Roaming\.minecraft\journeymap\data\mp\FinalScore_id_~4096083208109196453\psi. Memory: 1728MB total, 1237MB free

**Comment by AzyxA** [comment]
It's not my server.  It's a server that a friend has been maintaining for about 11 years. 
https://finalscoremc.com/faq/

Just connecting using the IP & port.

**Comment by mysticdrew** [comment]
Upload your logs to a log site, gist/pastbin or upload your journeymap.log and latest.log files in github here. Simply drop the files in the chat window. 
Pasting the log contents in the text box is not acceptable and difficult to read. 

> Just connecting using the IP & port.

using the multiplayer menu or a mod that connects you from the main title screen in minecraft?

**Comment by mysticdrew** [comment]
It looks like there is probably an issue with the server sending a random seedhash every login or you are logging into different worlds on the server. 

You can disable Multiworld support in the advanced options of journeymap and it wont use the seedhash id anymore. 
But, if the user uses "minecraft:overworld" for all their worlds you will get map overwriting.

**Comment by AzyxA** [comment]
Yeah, it was the Muli World Support option that was causing a new mp folder to be created with every login.
