### ISSUE TITLE
NPE being spammed in Client log

### ISSUE THREAD

**Issue by CoolDCB** [TeamJM/journeymap#589]
### What happened?

The client log is spammed with an NPE, I am unsure whether this is related to/causing other issues as the user with this spam is experiencing bugs with another mod too 

### Mod Loader

Forge

### Minecraft Version

1.18.2

### Version

5.9.4

### Relevant log output

I'm not sending the entire log publicly due to privacy concerns- the relevant error from the logs is below:

> java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.PlayerInfo.m_105312_()" because "info" is null
	at journeymap.common.util.PlayerRadarManager.buildPlayer(PlayerRadarManager.java:73) ~[journeymap-1.18.2-5.9.4-forge.jar%2395!/:1.18.2-5.9.4]
	at journeymap.common.util.PlayerRadarManager.updatePlayers(PlayerRadarManager.java:51) ~[journeymap-1.18.2-5.9.4-forge.jar%2395!/:1.18.2-5.9.4]
	at journeymap.common.network.handler.ClientPacketHandler.onPlayerLocationPacket(ClientPacketHandler.java:48) ~[journeymap-1.18.2-5.9.4-forge.jar%2395!/:1.18.2-5.9.4]
	at journeymap.common.network.packets.ServerPlayerLocationPacket.handle(ServerPlayerLocationPacket.java:101) ~[journeymap-1.18.2-5.9.4-forge.jar%2395!/:1.18.2-5.9.4]
	at journeymap.common.network.forge.ForgeNetworkHandler.lambda$buildHandler$4(ForgeNetworkHandler.java:71) ~[journeymap-1.18.2-5.9.4-forge.jar%2395!/:1.18.2-5.9.4]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at journeymap.common.network.forge.ForgeNetworkHandler.lambda$buildHandler$5(ForgeNetworkHandler.java:68) ~[journeymap-1.18.2-5.9.4-forge.jar%2395!/:1.18.2-5.9.4]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%2336!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%2336!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.2.0-universal.jar%23134!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1824) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2351!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]

**Comment by mysticdrew** [comment]
Do not copy paste logs.

Drop the whole log file in

**Comment by CoolDCB** [comment]
> Do not copy paste logs.
> 
> Drop the whole log file in

I explained at the top of the logs section as to why I did not. If you'd like further information I'd be happy to send you whatever you need from the logs privately, "I'm not sending the entire log publicly due to privacy concerns"

**Comment by mysticdrew** [comment]
There is no private information in the logs. 

When you create an issue, the log section clearly states "Do not copy and paste the logs or the issue will be closedl"
![image](https://user-images.githubusercontent.com/5459941/234978468-832ba3c0-a91d-4c67-b0bf-9caa37bb9f74.png)

**Comment by CoolDCB** [comment]
> There is no private information in the logs.
> 
> When you create an issue, the log section clearly states "Do not copy and paste the logs or the issue will be closedl" ![image](https://user-images.githubusercontent.com/5459941/234978468-832ba3c0-a91d-4c67-b0bf-9caa37bb9f74.png)

There is information within the logs that I legally cannot share with you. There is also nothing more in these logs that is by any means relevant to the NPE.

**Comment by mysticdrew** [comment]
I find that hard to believe. 
Anyways, feel free to delete the "legal" information and upload both logs please.

**Comment by CoolDCB** [comment]
We're going to do further research into other stuff that could be causing this error. I am unable to send you the logs whether cut down or not I'm afraid.
