### ISSUE TITLE
Crash if Realm name contains special characters 

### ISSUE THREAD

**Issue by nyanloutre** [TeamJM/journeymap#627]
Hello,

I am trying to join a Realm with a e-acute in it's name, the mod crash and the minimap is not shown.

Here is the tracelog of the crash :

```
[15:25:29] [Render thread/ERROR] [UIManager] Error drawing minimap: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /run/media/mmcblk0p1/minecraft/instances/1.19.4/.minecraft/journeymap/data/mp/La R?publique du Yaganda/overworld
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:121)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:68)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.io.File.toPath(File.java:2387)
	at journeymap.client.io.FileHandler.getDimPath(FileHandler.java:75)
	at journeymap.client.model.RegionCoord.<init>(RegionCoord.java:38)
	at journeymap.client.io.RegionImageHandler.getTileDrawSteps(RegionImageHandler.java:240)
	at journeymap.client.render.map.Tile.updateTexture(Tile.java:125)
	at journeymap.client.render.map.Tile.create(Tile.java:67)
	at journeymap.client.render.map.GridRenderer.findTile(GridRenderer.java:724)
	at journeymap.client.render.map.GridRenderer.center(GridRenderer.java:253)
	at journeymap.client.ui.minimap.MiniMap.initGridRenderer(MiniMap.java:156)
	at journeymap.client.ui.minimap.MiniMap.reset(MiniMap.java:726)
	at journeymap.client.ui.UIManager.drawMiniMap(UIManager.java:333)
	at journeymap.client.event.handlers.HudOverlayHandler.onRenderOverlay(HudOverlayHandler.java:90)
	at journeymap.client.event.fabric.FabricEventHandlerManager.onRenderOverlay(FabricEventHandlerManager.java:123)
	at net.minecraft.class_329.handler$bca000$journeymap$renderPre(class_329.java:2879)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by mysticdrew** [comment]
No versions
