### ISSUE TITLE
[1.12.2] Mobs disappear on minimap when overwriting vanilla animal renderers

### ISSUE THREAD

**Issue by itsmeow** [TeamJM/journeymap#71]
#### JourneyMap Version:

`1.12.2-5.5.2`

#### Forge Version:

`1.12.2-14.23.4.2705`

#### Describe the problem in repeatable steps:

1. Install https://minecraft.curseforge.com/projects/better-animal-models
2. Go near mob
3. Look on minimap, invisible

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
```
[15:22:17] [main/ERROR] [FileHandler] Couldn't locate icons for Default: C:\Users\hiotewdew\Desktop\CURRENT%20ENV\betteranimals-q\forge\run\.\mods\journeymap-1.12.2-5.5.2.jar\assets\journeymap\icon\entity
[15:22:17] [main/INFO] [IconSetFileHandler] Added entity icons from journeymap:icon/entity. Success: false
[15:22:17] [main/TRACE] [ThemeLoader] Initializing themes ...
[15:22:17] [main/ERROR] [FileHandler] Couldn't locate icons for flat: C:\Users\hiotewdew\Desktop\CURRENT%20ENV\betteranimals-q\forge\run\.\mods\journeymap-1.12.2-5.5.2.jar\assets\journeymap\theme\flat
[15:22:17] [main/INFO] [ThemeLoader] Preloaded theme textures: 0
[15:22:17] [main/DEBUG] [JourneymapClient] postInitialize EXIT, elapsed§8 count §r1§8 avg §r567.58§8ms§r
[15:22:17] [JM-VersionCheck-1/ERROR] [VersionCheck$1] Could not check version URL
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:134) [VersionCheck$1.class:1.12.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_172]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
	... 7 more

[15:22:41] [Server thread/ERROR] [DataCache] ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:863)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[15:22:41] [Server thread/ERROR] [WorldEventHandler] Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:863) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[15:22:41] [Server thread/ERROR] [DataCache] ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303)
	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190)
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_WorldEventHandler_onUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:863)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441)
	at journeymap.client.data.PlayerData.load(PlayerData.java:86)
	at journeymap.client.data.PlayerData.load(PlayerData.java:30)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 15 more

[15:22:41] [Server thread/ERROR] [WorldEventHandler] Error handling WorldEvent.Unload
java.lang.NullPointerException: null
	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) [WorldEventHandler.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_WorldEventHandler_onUnload_Unload.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:381) [DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:863) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[15:22:46] [main/WARN] [PropertiesBase] core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[15:22:46] [main/WARN] [PropertiesBase] core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
```

**Comment by BrainStone** [comment]
You might want to read the issue instructions...

**Comment by itsmeow** [comment]
Things of note: journeymap/icon/entity is empty.

**Comment by itsmeow** [comment]
Also, log seems to include #56 as well

**Comment by mysticdrew** [comment]
Logs here have nothing to do with your issue. 
We cannot anticipate what other mods do, there are lots of mods. Tell them to render their animals like vanilla.
