### ISSUE TITLE
Journey map error/ help pls.

### ISSUE THREAD

**Issue by FarmPumkin** [TeamJM/journeymap#72]
#### JourneyMap Version:

1.12.2-5.5.2
 
#### Forge Version:

1.12.2-14.23.5.2768

Load the mod but when enter it closes, and this comes out..
Please help  :(

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[17:14:45] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:14:45] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:14:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:14:45] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[17:14:45] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_181, running on Windows 7:x86:6.1, installed at C:\Program Files\Java\jre1.8.0_181
[17:14:46] [main/INFO] [FML]: Searching C:\Users\Edgar\AppData\Roaming\.minecraft\mods for mods
[17:14:46] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E2.jar
[17:14:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:14:46] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[17:14:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:14:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:14:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:14:46] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[17:14:46] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[17:14:46] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[17:14:46] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[17:14:46] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\Edgar\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_E2.jar
[17:14:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:14:49] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:14:50] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:14:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:14:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:14:50] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:14:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:14:50] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[17:14:50] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:14:51] [main/INFO] [minecraft/Minecraft]: Setting user: FarmPumpkin
[17:14:58] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[17:14:58] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[17:14:58] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[17:15:00] [main/INFO] [Config]: [OptiFine] *** Reflector Vanilla ***
[17:15:00] [main/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[17:15:00] [main/WARN] [minecraft/GameSettings]: Skipping bad option: streamPreferredServer:
[17:15:00] [main/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[17:15:00] [main/INFO] [Config]: [OptiFine] 
[17:15:00] [main/INFO] [Config]: [OptiFine] OptiFine_1.12.2_HD_U_E2
[17:15:00] [main/INFO] [Config]: [OptiFine] Build: 20180728-185429
[17:15:00] [main/INFO] [Config]: [OptiFine] OS: Windows 7 (x86) version 6.1
[17:15:00] [main/INFO] [Config]: [OptiFine] Java: 1.8.0_181, Oracle Corporation
[17:15:00] [main/INFO] [Config]: [OptiFine] VM: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
[17:15:00] [main/INFO] [Config]: [OptiFine] LWJGL: 2.9.4
[17:15:00] [main/INFO] [Config]: [OptiFine] OpenGL: Intel(R) G41 Express Chipset, version 2.1.0 - Build 8.15.10.2869, Intel
[17:15:00] [main/INFO] [Config]: [OptiFine] OpenGL Version: 2.1.0
[17:15:00] [main/INFO] [Config]: [OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
[17:15:00] [main/INFO] [Config]: [OptiFine] Maximum texture size: 4096x4096
[17:15:00] [VersionCheck/INFO] [Config]: [OptiFine] Checking for new version
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] ShadersMod version: 2.4.12
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] OpenGL Version: 2.1.0 - Build 8.15.10.2869
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Vendor:  Intel
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Renderer: Intel(R) G41 Express Chipset
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Capabilities:  2.0  2.1  -  -  - 
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Load ShadersMod configuration.
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shaders can not be loaded, Fast Render is enabled.
[17:15:00] [main/INFO] [net.optifine.shaders.SMCLog]: [Shaders] No shaderpack loaded.
[17:15:01] [main/INFO] [Config]: [OptiFine] [Shaders] Delayed loading of block mappings after resources are loaded
[17:15:01] [main/INFO] [Config]: [OptiFine] VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
[17:15:01] [main/WARN] [minecraft/ResourcePackRepository]: Removed selected resource pack Conquest_.zip because it's no longer compatible
[17:15:01] [main/WARN] [minecraft/ResourcePackRepository]: Removed selected resource pack conquest_shaders.zip because it's no longer compatible
[17:15:01] [main/INFO] [FML]: Forge Mod Loader has detected optifine OptiFine_1.12.2_HD_U_E2, enabling compatibility features
[17:15:01] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 381832664 bytes (364 MB) / 553648128 bytes (528 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 9 total; -Xmx1G -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2869' Renderer: 'Intel(R) G41 Express Chipset'
[17:15:01] [main/INFO] [FML]: MinecraftForge v14.23.5.2768 Initialized
[17:15:01] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[17:15:01] [main/INFO] [FML]: Replaced 1036 ore ingredients
[17:15:01] [VersionCheck/INFO] [Config]: [OptiFine] Version found: D1
[17:15:01] [main/INFO] [FML]: Searching C:\Users\Edgar\AppData\Roaming\.minecraft\mods for mods
[17:15:03] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 214444120 nanos
[17:15:05] [main/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[17:15:05] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, journeymap] at CLIENT
[17:15:05] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, journeymap] at SERVER
[17:15:06] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:JourneyMap
[17:15:06] [main/INFO] [FML]: Processing ObjectHolder annotations
[17:15:06] [main/INFO] [FML]: Found 1169 ObjectHolder annotations
[17:15:06] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[17:15:06] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[17:15:06] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:15:06] [main/INFO] [journeymap]: No plugins for JourneyMap API discovered.
[17:15:06] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[17:15:06] [main/INFO] [FML]: Applying holder lookups
[17:15:06] [main/INFO] [FML]: Holder lookups applied
[17:15:06] [main/INFO] [FML]: Applying holder lookups
[17:15:06] [main/INFO] [FML]: Holder lookups applied
[17:15:06] [main/INFO] [FML]: Applying holder lookups
[17:15:06] [main/INFO] [FML]: Holder lookups applied
[17:15:06] [main/INFO] [FML]: Applying holder lookups
[17:15:06] [main/INFO] [FML]: Holder lookups applied
[17:15:06] [main/INFO] [FML]: Injecting itemstacks
[17:15:06] [main/INFO] [FML]: Itemstack injection complete
[17:15:06] [main/INFO] [Config]: [OptiFine] *** Reloading textures ***
[17:15:06] [main/INFO] [Config]: [OptiFine] Resource packs: Default
[17:15:07] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[17:15:09] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[17:15:09] [Thread-5/INFO] [minecraft/SoundManager]: Initializing LWJGL OpenAL
[17:15:09] [Thread-5/INFO] [minecraft/SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:15:10] [Thread-5/INFO] [minecraft/SoundManager]: OpenAL initialized.
[17:15:10] [Sound Library Loader/INFO] [minecraft/SoundManager]: Sound engine started
[17:15:18] [main/INFO] [Config]: [OptiFine] Mipmap levels: 4
[17:15:18] [main/INFO] [Config]: [OptiFine] Multitexture: false
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_pane_white.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_white.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_pane_purple.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_purple.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_blue.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_pane_blue.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_brown.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_pane_brown.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_green.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_pane_green.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_pane_red.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_red.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_black.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_pane_black.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_orange.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_pane_orange.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_magenta.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_pane_magenta.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_light_blue.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_pane_light_blue.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_pane_yellow.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_yellow.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_lime.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_pane_lime.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pane_pink.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pink.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_gray.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_pane_gray.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_pane_silver.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_silver.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_cyan.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_pane_cyan.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/bookshelf.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glass.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glasspane.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] ConnectedTextures: mcpatcher/ctm/default/sandstone.properties
[17:15:18] [main/INFO] [Config]: [OptiFine] Multipass connected textures: false
[17:15:18] [main/INFO] [Config]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[17:15:25] [main/INFO] [Config]: [OptiFine] Custom loader sprites: 3
[17:15:25] [main/INFO] [Config]: [OptiFine] Sprite dependencies: 5
[17:15:25] [main/INFO] [minecraft/TextureMap]: Created: 1024x512 textures-atlas
[17:15:25] [main/INFO] [Config]: [OptiFine] Animated sprites: 22
[17:15:27] [main/INFO] [FML]: Applying holder lookups
[17:15:27] [main/INFO] [FML]: Holder lookups applied
[17:15:29] [main/ERROR] [journeymap]: Default theme not found in C:\Users\Edgar\AppData\Roaming\.minecraft\journeymap\icon\theme\flat\OceanMonument.theme2.json: OceanMonument (SUPPRESSED)
[17:15:29] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[17:15:29] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[17:15:29] [main/INFO] [journeymap]: JourneyMap log initialized.
[17:15:29] [main/INFO] [journeymap]: initialize ENTER
[17:15:29] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[17:15:29] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[17:15:29] [main/INFO] [journeymap]: [ClientAPI] built with JourneyMap API 1.4
[17:15:29] [main/INFO] [journeymap]: Initializing plugins with Client API: journeymap.client.api.impl.ClientAPI
[17:15:29] [main/INFO] [journeymap]: initialize EXIT, elapsed count 0 avg ?ms
[17:15:30] [main/INFO] [FML]: Injecting itemstacks
[17:15:30] [main/INFO] [FML]: Itemstack injection complete
[17:15:30] [main/INFO] [journeymap]: Added entity icons from journeymap:icon/entity. Success: false
[17:15:31] [main/INFO] [journeymap]: Preloaded theme textures: 71
[17:15:31] [main/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[17:15:31] [main/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[17:15:31] [main/WARN] [minecraft/GameSettings]: Skipping bad option: streamPreferredServer:
[17:15:31] [main/INFO] [mojang/NarratorWindows]: Narrator library for x86 successfully loaded
[17:15:31] [JM-VersionCheck-1/ERROR] [journeymap]: Could not check version URL
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[JsonParser.class:?]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:134) [VersionCheck$1.class:1.12.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
	... 7 more
[17:15:32] [main/INFO] [Config]: [OptiFine] *** Reloading custom textures ***

**Comment by FarmPumkin** [comment]
[16:00:07] [main/ERROR] [journeymap]: Default theme not found in C:\Users\Edgar\AppData\Roaming\.minecraft\journeymap\icon\theme\flat\OceanMonument.theme2.json: OceanMonument (SUPPRESSED)

[16:00:10] [JM-VersionCheck-1/ERROR] [journeymap]: Could not check version URL

**Comment by mysticdrew** [comment]
That exception is not a crash.
