### ISSUE TITLE
[Crash]: Can't compile shader on Linux

### ISSUE THREAD

**Issue by Binero** [TeamJM/journeymap#730]
### What happened?

When I run my game having just Fabric Loader, Fabric API and Journeymap, the game loads forever before even reaching the main menu. In the log the exceptions attached below fire.

| **Category**                 |    **Information** |
| ---------------------------- | -----------------: |
| **OS**                       |         Arch Linux |
| **Kernel**                   |       6.9.4 x86_64 |
| **GPU**                      | Radeon RX 7900 XTX |
| **Driver Version**           |        Mesa 24.1.1 |
| **OpenGL Version**           | 4.6 (Core Profile) |
| **Shading Language Version** |               4.60 |
| **Java Version**             |   OpenJDK JRE 21.9 |
| **Minecraft**                |               1.21 |
| **Fabric Loader**            |            0.15.11 |
| **Fabric API**               |       0.100.3+1.21 |
| **Journeymap**               |  1.21-6.0.0-beta.5 |

I have had a friend reproduce this issue on Fedora Linux on a different machine.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

```
[18:18:17] [Render thread/INFO]: OpenGL debug message: id=2, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:19(2): error: `return' with wrong type int, in function `trunc' returning float'
[18:18:17] [Render thread/INFO]: OpenGL debug message: id=3, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:22(2): error: `return' with wrong type int, in function `trunc' returning float'
[18:18:17] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at net.minecraft.class_757.md6b13f3$journeymap$lambda$modify$2$1(class_757.java:2591) ~[client-intermediary.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_757.localvar$znn000$journeymap$modify(class_757.java:2579) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:475) [client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/sepia_1.json: Couldn't compile fragment program (journeymap, sepia_1) : 0:19(2): error: `return' with wrong type int, in function `trunc' returning float
0:22(2): error: `return' with wrong type int, in function `trunc' returning float
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.md6b13f3$journeymap$lambda$modify$2$1(class_757.java:2584) ~[client-intermediary.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_757.localvar$znn000$journeymap$modify(class_757.java:2579) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:475) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
Caused by: java.io.IOException: Couldn't compile fragment program (journeymap, sepia_1) : 0:19(2): error: `return' with wrong type int, in function `trunc' returning float
0:22(2): error: `return' with wrong type int, in function `trunc' returning float
	at net.minecraft.class_281.method_34416(class_281.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:210) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:158) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.md6b13f3$journeymap$lambda$modify$2$1(class_757.java:2584) ~[client-intermediary.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_757.localvar$znn000$journeymap$modify(class_757.java:2579) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:475) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
```

**Comment by mysticdrew** [comment]
You are going to have to come into our discord to help resolve this as I do not have a way to test your exact setup.

**Comment by mysticdrew** [comment]
fixed in beta.6
