### ISSUE TITLE
[Bug]: vulkanmod breaks map rendering

### ISSUE THREAD

**Issue by UltraBlackLinux** [TeamJM/journeymap#760]
### What happened?

if combined with vulkanmod, the map renders entirely gray. Chunk borders and the like render fine, it's just the map that's missing.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

```
[14:10:13] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: at index 1
[14:10:13] [Render thread/INFO]: [STDERR]: 	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:232)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:222)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:216)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:353)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at com.google.common.collect.ImmutableList.of(ImmutableList.java:225)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1921$class_4688.<init>(class_1921.java:974)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1921$class_4688$class_4689.method_24297(class_1921.java:1088)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1921$class_4688$class_4689.method_23617(class_1921.java:1084)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.render.JMRenderTypes.getRegionTile(JMRenderTypes.java:218)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.render.map.RegionTile.render(RegionTile.java:70)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.render.map.MapRenderer.render(MapRenderer.java:209)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:332)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:204)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.ui.UIManager.drawMiniMap(UIManager.java:393)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.event.handlers.HudOverlayHandler.onRenderOverlay(HudOverlayHandler.java:119)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at journeymap.client.event.FabricEventHandlerManager.lambda$registerFabricEvents$3(FabricEventHandlerManager.java:76)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_329.handler$zpf000$fabric-rendering-v1$render(class_329.java:2038)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_329.method_1753(class_329.java:220)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:896)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1285)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[14:10:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
```
[14:10:13] [Render thread/WARN] [RegionTexture] Can't bind texture: 
java.lang.UnsupportedOperationException: null
	at net.vulkanmod.gl.GlTexture.texImage2D(GlTexture.java:79) ~[VulkanMod_1.21-0.4.3.jar:?]
	at com.mojang.blaze3d.platform.GlStateManager._texImage2D(GlStateManager.java:947) ~[client-intermediary.jar:?]
	at journeymap.client.render.RenderWrapper.texImage2D(RenderWrapper.java:267) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.texture.RegionTexture.method_23207(RegionTexture.java:84) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.render.map.RegionTile.updateRegionTexture(RegionTile.java:163) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.render.map.RegionTile.render(RegionTile.java:56) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.render.map.MapRenderer.render(MapRenderer.java:209) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:332) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.ui.minimap.MiniMap.drawMap(MiniMap.java:204) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.ui.UIManager.drawMiniMap(UIManager.java:393) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.event.handlers.HudOverlayHandler.onRenderOverlay(HudOverlayHandler.java:119) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at journeymap.client.event.FabricEventHandlerManager.lambda$registerFabricEvents$3(FabricEventHandlerManager.java:76) ~[journeymap-fabric-1.21-6.0.0-beta.17.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28) ~[fabric-rendering-v1-5.0.4+5a8c785ed1-fa840451f31c6009.jar:?]
	at net.minecraft.class_329.handler$zpf000$fabric-rendering-v1$render(class_329.java:2038) [client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:220) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:896) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[14:10:13] [Render thread/ERROR] [MapRenderer] Error drawing map tiles
```

**Comment by mysticdrew** [comment]
What version of vulkan and journeymap?

**Comment by mysticdrew** [comment]
I just talked to Collateral, the vulkanmod dev. He had not released the version that fixes journeymap support yet. 
I'll close this since it's no longer a jm issue. 

Collateral and I worked hard on making sure we are compatible. I have no eta when he'll release.
