### ISSUE TITLE
[Crash]: class ... cannot be cast to class ... and net.minecraft.registry.entry.RegistryEntry are in unnamed module of loader

### ISSUE THREAD

**Issue by HatTrkPatrk** [TeamJM/journeymap#781]
### What happened?

Server crashed (I wasn't online at the time it happened). I asked players who were online at the time and they didn't note anything unusual happening at the time, they were just randomly kicked because the server closed.

```
[16:16:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: class net.minecraft.world.chunk.PalettedContainer$PaletteProvider$Anonymous$851d4bc99c074b63ba0717efc8d31523 cannot be cast to class net.minecraft.registry.entry.RegistryEntry (net.minecraft.world.chunk.PalettedContainer$PaletteProvider$Anonymous$851d4bc99c074b63ba0717efc8d31523 and net.minecraft.registry.entry.RegistryEntry are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6be46e8f)
	at MC/net.minecraft.registry.Registry$1.getRawId(Registry.java:186) ~[server-intermediary.jar:?]
	at MC/net.minecraft.world.chunk.ArrayPalette.getPacketSize(ArrayPalette.java:100) ~[server-intermediary.jar:?]
	at MC/net.minecraft.world.chunk.PalettedContainer$Data.getPacketSize(PalettedContainer.java:321) ~[server-intermediary.jar:?]
	at MC/net.minecraft.world.chunk.PalettedContainer.getPacketSize(PalettedContainer.java:275) ~[server-intermediary.jar:?]
	at MC/net.minecraft.world.chunk.ChunkSection.getPacketSize(ChunkSection.java:176) ~[server-intermediary.jar:?]
	at MC/net.minecraft.network.packet.s2c.play.ChunkData.getSectionsPacketSize(ChunkData.java:80) ~[server-intermediary.jar:?]
	at MC/net.minecraft.network.packet.s2c.play.ChunkData.<init>(ChunkData.java:42) ~[server-intermediary.jar:?]
	at MC/net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.mixinextras$bridge$newclass_6603$15(ChunkDataS2CPacket.java) ~[server-intermediary.jar:?]
	at MC/net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.wrapOperation$zcg000$antixray$setChunkPacketInfoArgument(ChunkDataS2CPacket.java:559) ~[server-intermediary.jar:?]
	at MC/net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.<init>(ChunkDataS2CPacket.java:28) ~[server-intermediary.jar:?]
	at MC/net.minecraft.server.network.ChunkDataSender.sendChunkData(ChunkDataSender.java:88) ~[server-intermediary.jar:?]
	at MC/net.minecraft.server.network.ChunkDataSender.mixinextras$bridge$method_52388$13(ChunkDataSender.java) ~[server-intermediary.jar:?]
	at MC/net.minecraft.server.network.ChunkDataSender.wrapOperation$zcm000$antixray$setBatchStartPacketArgument(ChunkDataSender.java:556) ~[server-intermediary.jar:?]
	at MC/net.minecraft.server.network.ChunkDataSender.sendChunkBatches(ChunkDataSender.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1045) ~[server-intermediary.jar:?]
	at MC/net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
and
```
[16:16:05] [luckperms-worker-3/WARN]: Unable to pass event UserDataRecalculateEvent to handler me.lucko.luckperms.fabric.listeners.FabricAutoOpListener$$Lambda/0x00007fa241601778
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.isDedicated()" because the return value of "journeymap.common.helpers.FabricHooks.getServer()" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:108) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.submitAsync(ThreadExecutor.java:67) ~[server-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.submitAndJoin(ThreadExecutor.java:91) ~[server-intermediary.jar:?]
	at me.lucko.luckperms.fabric.FabricSchedulerAdapter.lambda$new$1(FabricSchedulerAdapter.java:37) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.common.plugin.scheduler.SchedulerAdapter.executeSync(SchedulerAdapter.java:65) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.fabric.listeners.FabricAutoOpListener.refreshAutoOp(FabricAutoOpListener.java:83) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.fabric.listeners.FabricAutoOpListener.lambda$onUserDataRecalculate$0(FabricAutoOpListener.java:57) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at me.lucko.luckperms.fabric.listeners.FabricAutoOpListener.onUserDataRecalculate(FabricAutoOpListener.java:57) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:94) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:42) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107) ~[event-3.0.0-remapped.jar:?]
	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:82) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:128) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.common.event.EventDispatcher.lambda$postAsync$0(EventDispatcher.java:143) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.isDedicated()" because the return value of "journeymap.common.helpers.FabricHooks.getServer()" is null
	at journeymap.common.helpers.FabricHooks.isDedicatedServer(FabricHooks.java:42) ~[journeymap-fabric-1.21-6.0.0-beta.22.jar:?]
	at journeymap.common.util.PermissionsManager.getPlayerConfig(PermissionsManager.java:45) ~[journeymap-fabric-1.21-6.0.0-beta.22.jar:?]
	at journeymap.common.util.PermissionsManager.sendPermissions(PermissionsManager.java:35) ~[journeymap-fabric-1.21-6.0.0-beta.22.jar:?]
	at journeymap.common.events.ServerEventHandler.sendConfigsToPlayer(ServerEventHandler.java:94) ~[journeymap-fabric-1.21-6.0.0-beta.22.jar:?]
	at journeymap.common.event.FabricServerEvents.onPermissionChangedEvent(FabricServerEvents.java:34) ~[journeymap-fabric-1.21-6.0.0-beta.22.jar:?]
	at MC/net.minecraft.server.PlayerManager.handler$ccj000$journeymap$deop(PlayerManager.java:5506) ~[server-intermediary.jar:?]
	at MC/net.minecraft.server.PlayerManager.removeFromOperators(PlayerManager.java:629) ~[server-intermediary.jar:?]
	at MC/net.minecraft.server.dedicated.DedicatedPlayerManager.removeFromOperators(DedicatedPlayerManager.java:50) ~[server-intermediary.jar:?]
	at me.lucko.luckperms.fabric.listeners.FabricAutoOpListener.lambda$setOp$3(FabricAutoOpListener.java:92) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at me.lucko.luckperms.fabric.listeners.FabricAutoOpListener.setOp(FabricAutoOpListener.java:88) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at me.lucko.luckperms.fabric.listeners.FabricAutoOpListener.lambda$refreshAutoOp$2(FabricAutoOpListener.java:83) ~[LuckPerms-Fabric-5.4.141.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.method_5386(ThreadExecutor.java:68) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 23 more
```

### Mod Loader

Fabric 0.16.2

### Minecraft Version

1.21

### Version

journeymap-fabric-1.21-6.0.0-beta.22

### Relevant log output

My log file is 1,269 KB so here's the part referencing the crash, if you need/want the rest of it I can upload it to a site.
[crash.txt](https://github.com/user-attachments/files/16822732/crash.txt)

**Comment by mysticdrew** [comment]
So the server crashed because of this. 
`java.lang.ClassCastException` the first error in the log which is not related to journeymap. 
Not really sure what caused that. 

The resulting errors from JM is because the shutdown process of the server was abruptly halted. Which is stemming from luckperms by the looks of it. 
I can prevent the exception or try to on journeymap's end. Just so it is not in the logs, but it wont fix your crash.
