### ISSUE TITLE
[Bug]: Crash from WaypointBeaconRenderer

### ISSUE THREAD

**Issue by schindlershadow** [TeamJM/journeymap#814]
### What happened?

Crash from WaypointBeaconRenderer

```
Description: Unexpected error

java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:?] {}
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(Unknown Source) ~[?:?] {}
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Unknown Source) ~[?:?] {}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.28/journeymap.client.render.ingame.WaypointBeaconRenderer.render(WaypointBeaconRenderer.java:29) ~[journeymap-neoforge-1.21.1-6.0.0-beta.28.jar%23627!/:1.21.1-6.0.0-beta.28] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.28/journeymap.client.event.handlers.WaypointBeaconHandler.onRenderWaypoints(WaypointBeaconHandler.java:40) ~[journeymap-neoforge-1.21.1-6.0.0-beta.28.jar%23627!/:1.21.1-6.0.0-beta.28] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.28/journeymap.client.event.handlers.WaypointBeaconHandler.onRenderWaypoints(WaypointBeaconHandler.java:54) ~[journeymap-neoforge-1.21.1-6.0.0-beta.28.jar%23627!/:1.21.1-6.0.0-beta.28] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.28/journeymap.client.event.NeoForgeRenderLevelStageEvent.onRenderWorldLastEvent(NeoForgeRenderLevelStageEvent.java:27) ~[journeymap-neoforge-1.21.1-6.0.0-beta.28.jar%23627!/:1.21.1-6.0.0-beta.28] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%23110!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%23110!/:?] {}
	at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.client.ClientHooks.dispatchRenderStage(ClientHooks.java:291) ~[neoforge-21.1.61-universal.jar%23472!/:?] {re:mixin,re:classloading,pl:mixin:APP:sodium-forge.mixins.json:ClientHooksMixin from mod sodium,pl:mixin:APP:journeymap.neoforge.mixins.json:client.ClientHooksMixin from mod journeymap,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1203) ~[client-1.21.1-20240808.144430-srg.jar%23471!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:default,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:default,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1271) ~[client-1.21.1-20240808.144430-srg.jar%23471!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1024) ~[client-1.21.1-20240808.144430-srg.jar%23471!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195) ~[client-1.21.1-20240808.144430-srg.jar%23471!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod sodium_extra,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod sodium_extra,pl:mixin:APP:neat.mixins.json:MinecraftMixin from mod neat,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod iris,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin from mod pickupnotifier,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin from mod itemphysic,pl:mixin:APP:customwindowtitle.mixins.json:DisableVanillaTitle from mod customwindowtitle,pl:mixin:APP:customwindowtitle.mixins.json:InitializeCustomIcon from mod customwindowtitle,pl:mixin:APP:aoa3.mixins.json:client.function.MinecraftMixin from mod aoa3,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft from mod glitchcore,pl:mixin:APP:midnightcontrols.mixins.json:MinecraftClientMixin from mod midnightcontrols,pl:mixin:APP:sodium.mixins.json:core.MinecraftMixin from mod sodium,pl:mixin:APP:sodium-forge.mixins.json:EntrypointMixin from mod sodium,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor from mod bettercombat,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject from mod bettercombat,pl:mixin:APP:extrasounds.mixins.json:hotbar.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds.mixins.json:inventory.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds-forge.mixins.json:forge.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:vampirism.mixins.json:client.MinecraftMixin from mod vampirism,pl:mixin:APP:globalpacks.mixins.json:MinecraftMixin from mod globalpacks,pl:mixin:APP:obsidianui.neoforge.mixins.json:MinecraftClientMixin from mod obsidianui,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:bookshelf.mixins.json:access.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:carryon.mixins.json:MinecraftMixin from mod carryon,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:memorysettings.mixins.json:MinecraftMixin from mod memorysettings,pl:mixin:APP:spyglass_improvements.common.mixins.json:MinecraftClientInvoker from mod spyglass_improvements,pl:mixin:APP:spyglass_improvements.common.mixins.json:MinecraftClientMixin from mod spyglass_improvements,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:l2menustacker.mixins.json:MinecraftMixin from mod l2menustacker,pl:mixin:APP:homeostatic_neoforge.mixins.json:MinecraftMixin from mod homeostatic,pl:mixin:APP:journeymap.mixins.json:client.MinecraftMixin from mod journeymap,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin from mod travelerstitles,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod moonlight,pl:mixin:APP:configuration.mixins.json:MinecraftMixin from mod configuration,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23471!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod sodium_extra,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod sodium_extra,pl:mixin:APP:neat.mixins.json:MinecraftMixin from mod neat,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod iris,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin from mod pickupnotifier,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:emojiful.mixins.json:MinecraftEmojifulMixin from mod emojiful,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin from mod itemphysic,pl:mixin:APP:customwindowtitle.mixins.json:DisableVanillaTitle from mod customwindowtitle,pl:mixin:APP:customwindowtitle.mixins.json:InitializeCustomIcon from mod customwindowtitle,pl:mixin:APP:aoa3.mixins.json:client.function.MinecraftMixin from mod aoa3,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft from mod glitchcore,pl:mixin:APP:midnightcontrols.mixins.json:MinecraftClientMixin from mod midnightcontrols,pl:mixin:APP:sodium.mixins.json:core.MinecraftMixin from mod sodium,pl:mixin:APP:sodium-forge.mixins.json:EntrypointMixin from mod sodium,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor from mod bettercombat,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject from mod bettercombat,pl:mixin:APP:extrasounds.mixins.json:hotbar.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds.mixins.json:inventory.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:extrasounds-forge.mixins.json:forge.MinecraftClientMixin from mod extrasounds,pl:mixin:APP:vampirism.mixins.json:client.MinecraftMixin from mod vampirism,pl:mixin:APP:globalpacks.mixins.json:MinecraftMixin from mod globalpacks,pl:mixin:APP:obsidianui.neoforge.mixins.json:MinecraftClientMixin from mod obsidianui,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:bookshelf.mixins.json:access.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:carryon.mixins.json:MinecraftMixin from mod carryon,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:memorysettings.mixins.json:MinecraftMixin from mod memorysettings,pl:mixin:APP:spyglass_improvements.common.mixins.json:MinecraftClientInvoker from mod spyglass_improvements,pl:mixin:APP:spyglass_improvements.common.mixins.json:MinecraftClientMixin from mod spyglass_improvements,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:l2menustacker.mixins.json:MinecraftMixin from mod l2menustacker,pl:mixin:APP:homeostatic_neoforge.mixins.json:MinecraftMixin from mod homeostatic,pl:mixin:APP:journeymap.mixins.json:client.MinecraftMixin from mod journeymap,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin from mod travelerstitles,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod moonlight,pl:mixin:APP:configuration.mixins.json:MinecraftMixin from mod configuration,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod yet_another_config_lib_v3,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23471!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%23118!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.24.jar%23118!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.24.jar%23118!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%23118!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23100!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23100!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23100!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23100!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23100!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23100!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23100!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
```

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

crash report https://pastebin.com/xKzPzujt
journeymap.log https://pastebin.com/tYuurBrL

**Comment by mysticdrew** [comment]
fixed in beta.29, it will be available in CF/MR shortly
