### ISSUE TITLE
[1.12.2] JourneyMap is using chunks from integrated server together with client chunks to generate map data

### ISSUE THREAD

**Issue by Barteks2x** [TeamJM/journeymap#88]
#### JourneyMap Version:

Most likely applies to all versions at least up to 5.5.3

#### Forge Version:

Applies to all forge versions

#### Describe the problem in repeatable steps:

It just happens to not cause any visible issues in vanilla. 

#### Relevant errors 
This problem can be proved to exist because it causes cubic chunks mod to corrupt the world and throw this exception: 
```
[19:27:47] [JM-task-4/ERROR]: Can't get blockId/meta for chunk -12,713 at BlockPos{x=-177, y=256, z=11408} : net.minecraft.util.ReportedException: Getting block state
	at net.minecraft.world.chunk.Chunk.func_186032_a(Chunk.java:515)
	at net.minecraft.world.chunk.Chunk.func_177435_g(Chunk.java:467)
	at journeymap.client.model.BlockMD.getBlockMD(BlockMD.java:242)
	at journeymap.client.model.BlockMD.getBlockMDFromChunkLocal(BlockMD.java:223)
	at journeymap.client.cartography.render.TopoRenderer.getBlockHeight(TopoRenderer.java:217)
	at journeymap.client.cartography.render.BaseRenderer.getOffsetBlockHeight(BaseRenderer.java:460)
	at journeymap.client.cartography.render.TopoRenderer.populateSlopes(TopoRenderer.java:293)
	at journeymap.client.cartography.render.TopoRenderer.render(TopoRenderer.java:131)
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:130)
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:122)
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72)
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:416)
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cube at 16 already exists!
	at io.github.opencubicchunks.cubicchunks.core.world.column.CubeMap.put(CubeMap.java:76)
	at net.minecraft.world.chunk.Chunk.addCube(Chunk.java:3617)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.onCubeLoaded(CubeProviderServer.java:331)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.generateCube(CubeProviderServer.java:404)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.postCubeLoadAttempt(CubeProviderServer.java:366)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:314)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:243)
	at net.minecraft.world.chunk.Chunk.getEBS_CubicChunks(Chunk.java:1764)
	at net.minecraft.world.chunk.Chunk.redirect$getBlockState_getMaxHeight$zzk000(Chunk.java:2001)
	at net.minecraft.world.chunk.Chunk.func_186032_a(Chunk.java:494)
	... 19 more
```

#### Code issue 

JourneyMap is listening to `ChunkEvent.Load` in ChunkMonitor class to know which chinks it's supposed to process. This event is fired once for server chunk and once for client chunk. While the event listener method is annotated with `@SideOnly(CLIENT)`, all it does is remove the method when running on dedicated server. The code is still called from both sides on singleplayer. 

I verified with byte code editor and later with a simple coremod that adding `if (!event.getWorld().isRemote) return;` makes JM not use server chunks anymore. 

For a long time I thought this is intentional (even if I didn't agree with it being done that way), until I've been told on discord to make this issue on github.

**Comment by mysticdrew** [comment]
Applied this fix in 5.5.4
