### ISSUE TITLE
[1.12.2] Client Bug: '/jm' autocomplete crash

### ISSUE THREAD

**Issue by JLBShecky** [TeamJM/journeymap#89]
#### JourneyMap Version:

1.12.1-5.5.3

#### Forge Version:

1.12.1-14.22.1.2478 and above.

#### Describe the problem in repeatable steps:

1. Start up the game with just forge and JourneyMap.
2. Create a creative or world with cheats enabled.
3. Enter "/jm " into the console.
4. Press tab for auto complete to have minecraft autocomplete statement with a ~, or do nothing.
5. Minecraft will crash to desktop.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

Nothing is added to the log file from the crash.

#### Relevant errors from `.minecraft/crash-reports/xxx.txt`

```
java.lang.NullPointerException: Updating screen events
	at net.minecraftforge.client.ClientCommandHandler.autoComplete(ClientCommandHandler.java:140)
	at net.minecraft.util.TabCompleter.func_186838_a(TabCompleter.java:65)
	at net.minecraft.util.TabCompleter.func_186841_a(TabCompleter.java:47)
	at net.minecraft.client.gui.GuiChat$ChatTabCompleter.func_186841_a(SourceFile:190)
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:70)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

### Notes

"/jtp " does not provide any tab auto completion, but is does not cause a crash to desktop. Also "/jtp" shows up in "/help" while "/jm" does not showup.

**Comment by mysticdrew** [comment]
Fixed in 5.5.4b2
